namespace Alchemy
{
    [ObjectAttr(nst: 680, ctr: 1056, align: 8)]
    public class CGuiSystemData : igObject
    {
        [FieldAttr(nst: 16, ctr: 16)] public CStringPauseMenuConfigurationHashTable? _pauseConfigurations;
        [FieldAttr(nst: 24, ctr: 24)] public igStringRefList? _streamedGuiProjectList;
        [FieldAttr(nst: 32, ctr: 32)] public igStringRefListList? _streamedGuiProjectGroups;
        [FieldAttr(nst: 40, ctr: 40)] public CControllerTypeToGuiInputSignalIconMaterialTable? _controllerTypeToGuiInputSignalIconTable;
        [FieldAttr(nst: 48, ctr: 48)] public CGuiMenuSoundTable? _globalGuiSoundData;
        [FieldAttr(nst: 56, ctr: 56)] public CGuiButtonLegendTable? _globalButtonLegendOptions;
        [FieldAttr(nst: 64, ctr: 64)] public CXButtonStringTable? _globalButtonCharacters;
        [FieldAttr(nst: 72)] public CXButtonStringTable? _kbVirtualButtonCharacters;
        [FieldAttr(nst: 80, ctr: 72)] public CControllerButtonCharacterMapList? _controllerSpecificMaps;
        [FieldAttr(nst: 88, ctr: 80)] public CControllerButtonCharacterMapList? _controllerVehicleSpecificMaps;
        [FieldAttr(nst: 96, ctr: 88)] public CGuiButtonLegendButtonList? _buttonLegendOrder;
        [FieldAttr(nst: 104, ctr: 96)] public igVec2fMetaField _defaultLegendPosition = new();
        [FieldAttr(nst: 112, ctr: 104)] public igVec2fMetaField _defaultVerticalLegendPosition = new();
        [FieldAttr(nst: 120, ctr: 112)] public igVec2fMetaField _defaultTabletVerticalLegendPosition = new();
        [FieldAttr(nst: 128, ctr: 120)] public int _numSpacesBetweenOptions = 4;
        [FieldAttr(nst: 136)] public CGuiKeyboardMenuList? _keyboardMenuOrder;
        [FieldAttr(nst: 144)] public CGuiKeyMappingTable? _keyboardMenuMappingTable;
        [FieldAttr(nst: 152)] public CGuiGraphicsMenuSettingTable? _graphicsMenuTable;
        [FieldAttr(nst: 160)] public CGuiGraphicsMenuSettingTable? _graphicsMenuDetails;
        [FieldAttr(nst: 168, ctr: 124)] public float _smallDeviceUIScaleFactor = 1.29999995f;
        [FieldAttr(nst: 176)] public CGuiMaterialHandleList? _questRankMaterials;
        [FieldAttr(nst: 184)] public CGuiMaterialHandleList? _giantsQuestRankMaterials;
        [FieldAttr(nst: 192, ctr: 128)] public igVec2fList? _damageNumberOffsets;
        [FieldAttr(nst: 200, ctr: 136)] public float _damageNumberCooldown = 0.5f;
        [FieldAttr(nst: 204)] public float _tutorialBroadcastRadius = 600.0f;
        [FieldAttr(nst: 208, ctr: 144)] public string? _titleMenuLevelName = "ui/mainmenubackground/mainmenubackground";
        [FieldAttr(nst: 216, ctr: 152)] public string? _loadingMenuName = "PVP_2017_Loading";
        [FieldAttr(nst: 224)] public string? _startScreenMenuName = "StartScreen_2015";
        [FieldAttr(ctr: 160)] public string? _pauseMenuName;
        [FieldAttr(ctr: 168)] public string? _saveLoadMenuName;
        [FieldAttr(ctr: 176)] public string? _dialogBoxMenuName;
        [FieldAttr(ctr: 184)] public string? _subtitlesMenuName;
        [FieldAttr(ctr: 192)] public string? _hintHudName;
        [FieldAttr(ctr: 200)] public string? _playerHudName;
        [FieldAttr(nst: 232, ctr: 208)] public string? _resultsScreenMenuName = null;
        [FieldAttr(nst: 240, ctr: 216)] public float _autoSaveLoopTime = 0.5f;
        [FieldAttr(nst: 244, ctr: 220)] public igVfxRangedCurveMetaField _autoSaveXPositionCurve = new();
        [FieldAttr(nst: 328, ctr: 304)] public igVfxRangedCurveMetaField _autoSaveYPositionCurve = new();
        [FieldAttr(nst: 412, ctr: 388)] public igVfxRangedCurveMetaField _autoSaveRotationCurve = new();
        [FieldAttr(nst: 496, ctr: 472)] public igVfxRangedCurveMetaField _autoSaveXScaleCurve = new();
        [FieldAttr(nst: 580, ctr: 556)] public igVfxRangedCurveMetaField _autoSaveYScaleCurve = new();
        [FieldAttr(nst: 664, ctr: 640)] public igVec2fMetaField _autoSaveIconDimensions = new();
        [FieldAttr(nst: 672)] public igStringRefList? _validTimeTrialInitialsCharacters;
        [FieldAttr(ctr: 648)] public CStringGuiColorStyleColorTable? _colorStyles;
        [FieldAttr(ctr: 656)] public CGuiOctaneLoadingScreenHintList? _loadingScreenHints;
        [FieldAttr(ctr: 664)] public CGuiOctaneLoadingScreenHintList? _battleLoadingScreenHints;
        [FieldAttr(ctr: 672)] public COctaneRaceModeNameTable? _raceModeDescriptions;
        [FieldAttr(ctr: 680)] public CGuiOctaneLoadingScreenHint? _durangoVoiceChatHint;
        [FieldAttr(ctr: 688)] public string? _durangoLevelToForceVoiceChatHint;
        [FieldAttr(ctr: 696)] public COctaneSubtitleDataTable? _moviesSubtitles;
        [FieldAttr(ctr: 704)] public COctaneCutsceneSubtitleDataTable? _cutscenesSubtitles;
        [FieldAttr(ctr: 712)] public COctaneRaceModeNameTable? _octaneRaceModeTable;
        [FieldAttr(ctr: 720)] public COctaneLeaderboardPopulationTable? _octaneLeaderboardPopulationTable;
        [FieldAttr(ctr: 728)] public CEntityFlagsColorTable? _teamColors;
        [FieldAttr(ctr: 736)] public CGuiOctaneAreaLevelListList? _raceAreaLevelDataList;
        [FieldAttr(ctr: 744)] public CGuiOctaneAreaLevelListList? _battleAreaLevelDataList;
        [FieldAttr(ctr: 752)] public string? _creditsMovieName;
        [FieldAttr(ctr: 760)] public CGuiItemTierColorTable? _itemTierColorTable;
        [FieldAttr(ctr: 768)] public igVec4ucMetaField _onlinePlayerTextColor = new();
        [FieldAttr(ctr: 772)] public igVec4ucMetaField _playerTextColor = new();
        [FieldAttr(ctr: 776)] public igVec4ucMetaField _noTierFocusedColor = new();
        [FieldAttr(ctr: 780)] public igVec4ucMetaField _noTierUnfocusedColor = new();
        [FieldAttr(ctr: 784)] public igVec4ucMetaField _playerOneColorA = new();
        [FieldAttr(ctr: 788)] public igVec4ucMetaField _playerOneColorB = new();
        [FieldAttr(ctr: 792)] public igVec4ucMetaField _playerTwoColorA = new();
        [FieldAttr(ctr: 796)] public igVec4ucMetaField _playerTwoColorB = new();
        [FieldAttr(ctr: 800)] public igVec4ucMetaField _playerThreeColorA = new();
        [FieldAttr(ctr: 804)] public igVec4ucMetaField _playerThreeColorB = new();
        [FieldAttr(ctr: 808)] public igVec4ucMetaField _playerFourColorA = new();
        [FieldAttr(ctr: 812)] public igVec4ucMetaField _playerFourColorB = new();
        [FieldAttr(ctr: 816)] public igVec3fMetaField _playerPositionScale = new();
        [FieldAttr(ctr: 828)] public igVec3fMetaField _nonPlayerPositionScale = new();
        [FieldAttr(ctr: 840)] public igStringRefList? _arenaWinnerTitles;
        [FieldAttr(ctr: 848)] public int _arenaWinnerTitlesDrawStartIndex;
        [FieldAttr(ctr: 856)] public igStringRefList? _arenaLoserTitles;
        [FieldAttr(ctr: 864)] public igStringRefList? _arenaTotalLoserTitles;
        [FieldAttr(ctr: 872)] public igStringRefList? _arenaSecondPlaceTitles;
        [FieldAttr(ctr: 880)] public igStringRefList? _arenaMostHitTitles;
        [FieldAttr(ctr: 888)] public string? _arenaNewLeader;
        [FieldAttr(ctr: 896)] public string? _arenaRacerEliminated;
        [FieldAttr(ctr: 904)] public string? _arenaTeamEliminated;
        [FieldAttr(ctr: 912)] public string? _arenaKartsToGo;
        [FieldAttr(ctr: 920)] public string? _arenaOneKartToGo;
        [FieldAttr(ctr: 928)] public string? _arenaFlagPicked;
        [FieldAttr(ctr: 936)] public string? _arenaFlagScore;
        [FieldAttr(ctr: 944)] public string? _arenaFlagCaptured;
        [FieldAttr(ctr: 952)] public string? _arenaFlagDropped;
        [FieldAttr(ctr: 960)] public string? _arenaTeamFlagDropped;
        [FieldAttr(ctr: 968)] public string? _arenaTeamFlagStolen;
        [FieldAttr(ctr: 976)] public string? _arenaTeamFlagPicked;
        [FieldAttr(ctr: 984)] public string? _arenaDrawText;
        [FieldAttr(ctr: 992)] public string? _arenaTryAgainText;
        [FieldAttr(ctr: 1000)] public igStringRefList? _guiProjectsWithoutBackgrounds;
        [FieldAttr(ctr: 1008)] public igStringRefList? _guiProjectsWithMovies;
        [FieldAttr(ctr: 1016)] public CLanguageStringHashTable? _EULAExtraPageNA;
        [FieldAttr(ctr: 1024)] public CLanguageStringHashTable? _EULAExtraPageEU;
        [FieldAttr(ctr: 1032)] public igStringRefList? _wheelsFilterStrings;
        [FieldAttr(ctr: 1040)] public igStringRefList? _paintjobsFilterStrings;
        [FieldAttr(ctr: 1048)] public CKartStickerFilterGroupNamesTable? _stickerFilterStringTable;
    }
}
