namespace Alchemy
{
    [ObjectAttr(nst: 488, ctr: 488, align: 8)]
    public class CGlobalTuningData : igObject
    {
        [FieldAttr(nst: 16, ctr: 16)] public CGlobalRenderData? _renderData;
        [FieldAttr(nst: 24, ctr: 24)] public float _wingedSapphireDiscount = 0.02f;
        [FieldAttr(nst: 28, ctr: 28)] public float _railSameRailJumpHeight = 300.0f;
        [FieldAttr(nst: 32, ctr: 32)] public float _railSameRailJumpTime = 1.0f;
        [FieldAttr(nst: 36, ctr: 36)] public float _railChangeRailsJumpHeight = 300.0f;
        [FieldAttr(nst: 40, ctr: 40)] public float _railChangeRailsJumpTime = 1.0f;
        [FieldAttr(nst: 44, ctr: 44)] public float _railJumpStickMagnitudeThreshold = 0.25f;
        [FieldAttr(nst: 48, ctr: 48)] public float _railJumpStickAngleThreshold = 120.0f;
        [FieldAttr(nst: 52, ctr: 52)] public float _railDistanceBetweenPlayers = 250.0f;
        [FieldAttr(nst: 56, ctr: 56)] public float _railDistanceBetweenPlayersBuffer = 50.0f;
        [FieldAttr(nst: 60, ctr: 60)] public float _railPlayerCatchupTime = 1.0f;
        [FieldAttr(nst: 64, ctr: 64)] public float _railLeaderTransitionTime = 1.0f;
        [FieldAttr(nst: 68, ctr: 68)] public float _minDelayTillDynamicCollectiblesAreCollectible = 1.0f;
        [FieldAttr(nst: 72, ctr: 72)] public float _maxDelayTillDynamicCollectiblesAreCollectible = 1.29999995f;
        [FieldAttr(nst: 76, ctr: 76)] public float _xpMultiplierPerLevelBelowTarget = 0.25f;
        [FieldAttr(nst: 80, ctr: 80)] public float _xpMultiplierMax = 3.0f;
        [FieldAttr(nst: 84, ctr: 84)] public int _xpMultiplierMapLevelOffset;
        [FieldAttr(nst: 88, ctr: 88)] public float _enemyDamageCoopScale = 1.25f;
        [FieldAttr(nst: 92, ctr: 92)] public float _enemyHealthCoopScale = 1.39999998f;
        [FieldAttr(nst: 96, ctr: 96)] public CDifficultySpecificFloat? _difficultyFixedEnemyDamageScale;
        [FieldAttr(nst: 104, ctr: 104)] public CDifficultySpecificFloat? _difficultyFixedEnemyHealthScale;
        [FieldAttr(nst: 112, ctr: 112)] public CDifficultySpecificInt? _difficultyFoodHealthGainPercentage;
        [FieldAttr(nst: 120, ctr: 120)] public CDifficultySpecificInt? _difficultyShieldRepairGainPercentage;
        [FieldAttr(nst: 128, ctr: 128)] public CDifficultySpecificFloat? _difficultyLevelUpHealthRecovery;
        [FieldAttr(nst: 136, ctr: 136)] public CDifficultySpecificFloat? _difficultyEnemyAttackCooldownMultiplier;
        [FieldAttr(nst: 144, ctr: 144)] public CDifficultySpecificFloat? _difficultyAirChaseCooldownMultiplier;
        [FieldAttr(nst: 152, ctr: 152)] public float _foodDropMediumHealthThreshold = 0.8f;
        [FieldAttr(nst: 156, ctr: 156)] public float _foodDropLowHealthThreshold = 0.4f;
        [FieldAttr(nst: 160, ctr: 160)] public CDifficultySpecificFloat? _foodDropCooldown;
        [FieldAttr(nst: 168, ctr: 168)] public CDifficultySpecificInt? _foodDropNormalChance;
        [FieldAttr(nst: 176, ctr: 176)] public CDifficultySpecificInt? _foodDropMediumHealthChance;
        [FieldAttr(nst: 184, ctr: 184)] public CDifficultySpecificInt? _foodDropLowHealthChance;
        [FieldAttr(nst: 192, ctr: 192)] public float _shieldDropLowShieldsThreshold = 0.4f;
        [FieldAttr(nst: 200, ctr: 200)] public CDifficultySpecificFloat? _shieldDropCooldown;
        [FieldAttr(nst: 208, ctr: 208)] public CDifficultySpecificInt? _shieldDropNormalChance;
        [FieldAttr(nst: 216, ctr: 216)] public CDifficultySpecificInt? _shieldDropLowShieldsChance;
        [FieldAttr(nst: 224, ctr: 224)] public float _difficultyBaseSkillLevel = 5.0f;
        [FieldAttr(nst: 232, ctr: 232)] public CDifficultySpecificFloat? _difficultyMinSkillLevel;
        [FieldAttr(nst: 240, ctr: 240)] public CDifficultySpecificFloat? _difficultyMaxSkillLevel;
        [FieldAttr(nst: 248, ctr: 248)] public float _difficultyHealthModifierStrength = 0.5f;
        [FieldAttr(nst: 252, ctr: 252)] public float _difficultyDamageModifierStrength = 1.0f;
        [FieldAttr(nst: 256, ctr: 256)] public float _difficultyDamageTimeOut = 3.0f;
        [FieldAttr(nst: 260, ctr: 260)] public float _difficultyIdleTimeOut = 12.0f;
        [FieldAttr(nst: 264, ctr: 264)] public float _difficultyIncreasingSkillMultiplier = 2.0f;
        [FieldAttr(nst: 268, ctr: 268)] public float _difficultyMaxDifficultyChange = 1.0f;
        [FieldAttr(nst: 272, ctr: 272)] public float _difficultyAdditionalTimePerDeath = 5.0f;
        [FieldAttr(nst: 276, ctr: 276)] public int _difficultyDeathCountForTrapdoor = 2;
        [FieldAttr(nst: 280, ctr: 280)] public int _difficultyMaxTrapdoors = 2;
        [FieldAttr(nst: 284, ctr: 284)] public float _difficultyTrapdoorSkillDecrease = 2.0f;
        [FieldAttr(nst: 288, ctr: 288)] public float _defaultCritMultiplier = 150.0f;
        [FieldAttr(nst: 292, ctr: 292)] public float _maxCritMultiplier = 200.0f;
        [FieldAttr(nst: 296, ctr: 296)] public float _maxCritChance = 50.0f;
        [FieldAttr(nst: 304, ctr: 304)] public igIntFloatHashTable? _levelHealthMultipliers;
        [FieldAttr(nst: 312, ctr: 312)] public igIntFloatHashTable? _levelHealthMultipliersPVP;
        [FieldAttr(nst: 320, ctr: 320)] public int _survivalAlmostPerfectLivesSolo = 4;
        [FieldAttr(nst: 324, ctr: 324)] public int _survivalAlmostPerfectLivesCoop = 4;
        [FieldAttr(nst: 328, ctr: 328)] public int _survivalAlmostPerfectLivesRival = 4;
        [FieldAttr(nst: 332, ctr: 332)] public int _battleModeRewardBaseGold = 80;
        [FieldAttr(nst: 336, ctr: 336)] public int _battleModeRewardBaseXP = 80;
        [FieldAttr(nst: 340, ctr: 340)] public float _battleModeRewardGoldRewardMultiplier = 0.44999999f;
        [FieldAttr(nst: 344, ctr: 344)] public float _battleModeRewardXPRewardMultiplier = 0.55f;
        [FieldAttr(nst: 348, ctr: 348)] public int _battleModeRewardMaxLevelDifferenceNoModification = 2;
        [FieldAttr(nst: 352, ctr: 352)] public int _battleModeRewardMaxLevelDifferenceModification = 6;
        [FieldAttr(nst: 356, ctr: 356)] public float _battleModeRewardWinnerLevelLowerMultiplier = 1.39999998f;
        [FieldAttr(nst: 360, ctr: 360)] public float _battleModeRewardWinnerLevelHigherMultiplier = 0.5f;
        [FieldAttr(nst: 364, ctr: 364)] public igRangedFloatMetaField _battleModeRewardRandomValueToAdd = new();
        [FieldAttr(nst: 372, ctr: 372)] public float _battleModeRewardLoserRatio = 0.5f;
        [FieldAttr(nst: 376, ctr: 376)] public igVec2fList? _battleModeRewardTimeMultipliers;
        [FieldAttr(nst: 384, ctr: 384)] public float _speedsterLeftRightTraversalSpeed = 200.0f;
        [FieldAttr(nst: 388, ctr: 388)] public float _speedsterNormalGravity = 385.0f;
        [FieldAttr(nst: 392, ctr: 392)] public float _speedsterAirStateGroundDistance = 100.0f;
        [FieldAttr(nst: 396, ctr: 396)] public float _speedsterMaxFallSpeed = 600.0f;
        [FieldAttr(nst: 400, ctr: 400)] public float _speedsterNormalSpeed = 1500.0f;
        [FieldAttr(nst: 404, ctr: 404)] public float _speedsterJumpForce = 3000.0f;
        [FieldAttr(nst: 408, ctr: 408)] public float _speedsterBoostSpeed = 2000.0f;
        [FieldAttr(nst: 412, ctr: 412)] public float _speedsterBoostDuration = 3.0f;
        [FieldAttr(nst: 416, ctr: 416)] public float _speedsterBoostCooldown = 15.0f;
        [FieldAttr(nst: 420, ctr: 420)] public float _speedsterBoostAcceleration = 300.0f;
        [FieldAttr(nst: 424, ctr: 424)] public float _speedsterBoostDeceleration = 300.0f;
        [FieldAttr(nst: 432, ctr: 432)] public CBoltPoint? _speedsterBoostButtonPromptBolt;
        [FieldAttr(nst: 440, ctr: 440)] public float _speedsterSlowSpeed = 500.0f;
        [FieldAttr(nst: 444, ctr: 444)] public float _speedsterSlowDuration = 3.0f;
        [FieldAttr(nst: 448, ctr: 448)] public float _speedsterSlowAcceleration = 300.0f;
        [FieldAttr(nst: 452, ctr: 452)] public float _speedsterSlowDeceleration = 300.0f;
        [FieldAttr(nst: 456, ctr: 456)] public float _speedsterSlowCooldown = 1.0f;
        [FieldAttr(nst: 460, ctr: 460)] public float _speedsterMaxLeanAngle = 30.0f;
        [FieldAttr(nst: 464, ctr: 464)] public float _speedsterLeanAngleSpeed = 60.0f;
        [FieldAttr(nst: 468, ctr: 468)] public float _speedsterAttachmentSpawnRange = 1000.0f;
        [FieldAttr(nst: 472, ctr: 472)] public float _superdropDeathFadeTime = 1.0f;
        [FieldAttr(nst: 476, ctr: 476)] public float _forceForwardLeftRightTraversalSpeed = 200.0f;
        [FieldAttr(nst: 480, ctr: 480)] public float _forceForwardMaxTwistAngle = 60.0f;
        [FieldAttr(nst: 484, ctr: 484)] public float _forceForwardTwistSpeed = 300.0f;
    }
}
