namespace Alchemy
{
    [ObjectAttr(nst: 1824, ctr: 2232, align: 8)]
    public class CGlobalPlatformStrings : igObject
    {
        [FieldAttr(nst: 16, ctr: 16)] public string? _yesString = "Yes";
        [FieldAttr(nst: 24, ctr: 24)] public string? _noString = "No";
        [FieldAttr(nst: 32, ctr: 32)] public string? _selectString = "Select";
        [FieldAttr(nst: 40, ctr: 40)] public string? _readString = "Read";
        [FieldAttr(nst: 48, ctr: 48)] public string? _restartString = "Restart";
        [FieldAttr(nst: 56, ctr: 56)] public string? _continueString = "Continue";
        [FieldAttr(nst: 64, ctr: 64)] public string? _resultsContinueString = "Continue";
        [FieldAttr(nst: 72, ctr: 72)] public string? _cancelString = "Cancel";
        [FieldAttr(nst: 80, ctr: 80)] public string? _mainMenuString = "Main Menu";
        [FieldAttr(nst: 88, ctr: 88)] public string? _tryAgainString = "Try Again";
        [FieldAttr(nst: 96, ctr: 96)] public string? _signInString = "Sign In";
        [FieldAttr(nst: 104, ctr: 104)] public string? _deleteString = "Delete";
        [FieldAttr(nst: 112, ctr: 112)] public string? _corruptString = "Corrupt";
        [FieldAttr(nst: 120, ctr: 120)] public string? _invalidString = "Invalid";
        [FieldAttr(nst: 128, ctr: 128)] public string? _playerString = "Player";
        [FieldAttr(nst: 136, ctr: 136)] public string? _playerNumberString = "Player %d";
        [FieldAttr(ctr: 144)] public string? _numberedGamertagString;
        [FieldAttr(nst: 144, ctr: 152)] public string? _legalString = "Legal";
        [FieldAttr(nst: 152, ctr: 160)] public string? _specialString = "Special";
        [FieldAttr(nst: 160, ctr: 168)] public string? _hubString = "the Academy";
        [FieldAttr(nst: 168, ctr: 176)] public string? _gameTitle = "Mack";
        [FieldAttr(nst: 176, ctr: 184)] public string? _playMovieString = "Play Movie";
        [FieldAttr(nst: 184, ctr: 192)] public string? _saveSlotString = "Save";
        [FieldAttr(nst: 192, ctr: 200)] public string? _autosaveSlotString = "Autosave Slot";
        [FieldAttr(nst: 200, ctr: 208)] public string? _emptySaveSlotString = "Empty";
        [FieldAttr(nst: 208, ctr: 216)] public string? _newGameString = "New Game";
        [FieldAttr(nst: 216, ctr: 224)] public string? _loadGameString = "Load Game";
        [FieldAttr(nst: 224, ctr: 232)] public string? _optionsSaveDescriptor = "Global Save";
        [FieldAttr(nst: 232, ctr: 240)] public string? _controllerDisconnected = null;
        [FieldAttr(nst: 240, ctr: 248)] public string? _goToLevelConfirmation = "Are you sure you want to travel to %s?";
        [FieldAttr(nst: 248, ctr: 256)] public string? _restartLevelConfirmation = "Are you sure you want to restart the level from the beginning?";
        [FieldAttr(nst: 256, ctr: 264)] public string? _restartCheckpointConfirmation = "You currently have a checkpoint saved for this level.  Do you want to start from the beginning or continue from the checkpoint?";
        [FieldAttr(nst: 264, ctr: 272)] public string? _quitToHubConfirmation = "Are you sure you want to return to the hub?  Any progress since the last save will be lost.";
        [FieldAttr(nst: 272, ctr: 280)] public string? _quitToHubConfirmationPeerOnline = "Are you sure you want to return to the Academy? You will leave this online game.";
        [FieldAttr(nst: 280, ctr: 288)] public string? _quitToMainMenuConfirmation = "Are you sure you want to exit the game and return to the Main Menu? Any progress since the last save will be lost.";
        [FieldAttr(ctr: 296)] public string? _quitCustomizationControllerDisconnectedConfirmation;
        [FieldAttr(ctr: 304)] public string? _quitCustomizationString;
        [FieldAttr(nst: 288, ctr: 312)] public string? _quitToMainMenuConfirmationHostOnline = "Are you sure you want to exit the game and return to the Main Menu? Progress since the last save will be lost and the online game will end.";
        [FieldAttr(nst: 296, ctr: 320)] public string? _quitToMainMenuConfirmationPeerOnline = "Are you sure you want to exit the game and return to the Main Menu? You will leave this online game.";
        [FieldAttr(nst: 304, ctr: 328)] public string? _notEnoughStorageSpaceWarning = "Not enough storage space remaining. Continue without saving?";
        [FieldAttr(nst: 312, ctr: 336)] public string? _notEnoughStorageSpaceOptionsWarning = "Not enough storage space remaining for global save. You will be unable to proceed until you clear enough space.";
        [FieldAttr(nst: 320, ctr: 344)] public string? _notEnoughStorageSpaceAutoSaveDisabledWarning = "Not enough storage space remaining. Autosave has been disabled (you can re-enable it in the save/load menu).";
        [FieldAttr(nst: 328, ctr: 352)] public string? _unableToConnectToCloud = "Unable to connect to iCloud. Retry or continue without saving.";
        [FieldAttr(nst: 336, ctr: 360)] public string? _unableToConnectToCloudTablet = "Unable to connect to iCloud. Retry or continue without iCloud.";
        [FieldAttr(nst: 344, ctr: 368)] public string? _continueWithoutCloudSave = "No iCloud";
        [FieldAttr(nst: 352, ctr: 376)] public string? _connectingToiCloud = "Connecting To iCloud";
        [FieldAttr(ctr: 384)] public string? _connecting;
        [FieldAttr(nst: 360, ctr: 392)] public string? _conflictFromDeviceFormat = "From %s";
        [FieldAttr(nst: 368, ctr: 400)] public string? _conflictSaveSlotWithSaveFormat = "Save %d";
        [FieldAttr(nst: 376, ctr: 408)] public string? _conflictSaveSlotNoSaveFormat = "Save %d";
        [FieldAttr(nst: 384, ctr: 416)] public string? _playFromCheckpointConfirmation = "You currently have a checkpoint saved for this level. Do you want to start from the beginning or continue from the checkpoint?";
        [FieldAttr(nst: 392, ctr: 424)] public string? _loseCheckpointWarning = "Playing this level will erase your checkpoint in %s. Are you sure you want to continue?";
        [FieldAttr(nst: 400, ctr: 432)] public string? _deleteSaveGameWarning = "Are you sure you want to delete this save game? All progress within this save slot will be lost.";
        [FieldAttr(nst: 408, ctr: 440)] public string? _invalidStorageDeviceError = "Your storage device was disconnected. You must restart the game and select a valid storage device, or continue without saving.";
        [FieldAttr(nst: 416, ctr: 448)] public string? _saveFileCorruptWarning = "Unable to load game. Save file is corrupt. You must delete the file or continue without saving.";
        [FieldAttr(nst: 424, ctr: 456)] public string? _overwriteCorruptSaveFileInfo = "Save file '%s' is corrupt and will be overwritten.";
        [FieldAttr(nst: 432, ctr: 464)] public string? _overwriteInvalidOwnerSaveFileInfo = "Access is denied to save file '%s' and it will be overwritten.";
        [FieldAttr(nst: 440, ctr: 472)] public string? _saveFileInvalidOwnerWarning = "This save is owned by another user and will be deleted.";
        [FieldAttr(nst: 448)] public string? _globalOptionsSaveCorruptWarning = "Global Options Save file is corrupt. You must delete the file or continue without saving.";
        [FieldAttr(nst: 456)] public string? _optionsSaveOutOfDateWarning = "Global Options Save file is the wrong version. You must delete the file or continue without saving options.";
        [FieldAttr(ctr: 480)] public string? _optionsSaveCorruptWarning;
        [FieldAttr(nst: 464, ctr: 488)] public string? _optionsSaveInvalidOwnerWarning = "Global Save is owned by another user and will be deleted.";
        [FieldAttr(nst: 472, ctr: 496)] public string? _unableToLoadCorruptSaveFileInfo = "Save file '%s' is corrupt and could not be loaded.";
        [FieldAttr(nst: 480, ctr: 504)] public string? _unableToLoadInvalidOwnerSaveFileInfo = "Access is denied to save file '%s' and it could not be loaded.";
        [FieldAttr(nst: 488, ctr: 512)] public string? _selectProfileWarning = "You do not have an active profile. You need to sign in with a profile to save, load, and delete game files.";
        [FieldAttr(nst: 496, ctr: 520)] public string? _iCloudSignInWarning = "Your iCloud account is unavailable. You need to be to signed in to save, load, and delete game files.";
        [FieldAttr(nst: 504, ctr: 528)] public string? _selectDeviceWarning = "You do not have a selected storage device. You need to select a storage device to save, load, and delete game files.";
        [FieldAttr(nst: 512, ctr: 536)] public string? _signInStatusChanged = "A sign in changed occurred. You must sign back in or restart the game.";
        [FieldAttr(nst: 520, ctr: 544)] public string? _signedInWhileSaveLoadDisabled = "A sign in change occurred. You are now being returned to the title screen.";
        [FieldAttr(nst: 528, ctr: 552)] public string? _switchProfile = "Switch Profile";
        [FieldAttr(nst: 536, ctr: 560)] public string? _viewFriendsText = "View Friends";
        [FieldAttr(nst: 544, ctr: 568)] public string? _viewGamercard = "Gamer Card";
        [FieldAttr(nst: 552, ctr: 576)] public string? _viewInvites = "Invites";
        [FieldAttr(nst: 560, ctr: 584)] public string? _viewCollection = "Collection";
        [FieldAttr(nst: 568, ctr: 592)] public string? _viewStats = "Stats";
        [FieldAttr(nst: 576, ctr: 600)] public string? _viewMyCollection = "My Collection";
        [FieldAttr(nst: 584, ctr: 608)] public string? _dialogBoxNotificationTitle = "NOTICE";
        [FieldAttr(nst: 592)] public string? _dialogBoxNetworkNotificationTitle = "NOTICE";
        [FieldAttr(ctr: 616)] public string? _dialogBoxWarningTitle;
        [FieldAttr(nst: 600, ctr: 624)] public string? _signinToViewLeaderboard = "Sign in to access online features.";
        [FieldAttr(nst: 608, ctr: 632)] public string? _wouldYouLikeToSignIn = "Would you like to sign in?";
        [FieldAttr(nst: 616, ctr: 640)] public string? _friendScoresUnavailable = "Unable to connect to servers. Friend Scores will be unavailable.";
        [FieldAttr(nst: 624, ctr: 648)] public string? _serverUnavailable = "Unable to connect to servers.";
        [FieldAttr(nst: 632, ctr: 656)] public string? _serverAvailable = "Connected to servers.";
        [FieldAttr(nst: 640, ctr: 664)] public string? _userSignOutOccured = "%s has been signed out.";
        [FieldAttr(nst: 648, ctr: 672)] public string? _onlineFeaturesNotAvailable = "You will not be able to play online.";
        [FieldAttr(nst: 656, ctr: 680)] public string? _cableUnplugged = "You have lost connection to your network.";
        [FieldAttr(nst: 664, ctr: 688)] public string? _networkDiagnostic = "Network diagnostic";
        [FieldAttr(nst: 672, ctr: 696)] public string? _friendListUnavailable = "Unable to retrieve friend list.";
        [FieldAttr(nst: 680, ctr: 704)] public string? _friendListEmpty = "Add friends to compare scores.";
        [FieldAttr(nst: 688, ctr: 712)] public string? _friendsListEmptyText = "Your friend list is empty.";
        [FieldAttr(nst: 696, ctr: 720)] public string? _friendsOnline = "Join a friend's game.";
        [FieldAttr(nst: 704, ctr: 728)] public string? _friendOnline = "Join %s's game.";
        [FieldAttr(nst: 712, ctr: 736)] public string? _friendStatusOnline = "Online";
        [FieldAttr(nst: 720, ctr: 744)] public string? _friendStatusOffline = "Offline";
        [FieldAttr(nst: 728, ctr: 752)] public string? _friendStatusJoinable = "Joinable";
        [FieldAttr(nst: 736, ctr: 760)] public string? _onlineStatusOnline = "Online";
        [FieldAttr(nst: 744, ctr: 768)] public string? _onlineStatusDoNotDisturb = "Do Not Disturb";
        [FieldAttr(ctr: 776)] public string? _nonJoinableFriend;
        [FieldAttr(nst: 752, ctr: 784)] public string? _unableToJoin = "Unable to join game.";
        [FieldAttr(nst: 760, ctr: 792)] public string? _unableToJoinSessionIsFull = "Unable to join game. The session is full.";
        [FieldAttr(nst: 768, ctr: 800)] public string? _unableToJoinHostMultiplayerNotPermitted = "Unable to join game. The host does not have access to multiplayer features.";
        [FieldAttr(nst: 776, ctr: 808)] public string? _unableToJoinHostAgeRestricted = "Unable to join game. Content is restricted on the host's account.";
        [FieldAttr(nst: 784, ctr: 816)] public string? _unableToJoinHostSearching = "Unable to join game. The host is searching for races.";
        [FieldAttr(nst: 792, ctr: 824)] public string? _unableToJoinHostSessionIsDoNotDisturb = "Unable to join game. The host's session is set to do not disturb.";
        [FieldAttr(nst: 800, ctr: 832)] public string? _unableToJoinHostInMatch = "Unable to join game. The host is playing a match.";
        [FieldAttr(nst: 808, ctr: 840)] public string? _unableToJoinHostInMainMenu = "Unable to join game. The host is at the main menu.";
        [FieldAttr(nst: 816, ctr: 848)] public string? _unableToJoinHostAddrIsNull = "Unable to join game. The host's address is null.";
        [FieldAttr(nst: 824, ctr: 856)] public string? _unableToJoinHostAddrIsLoopback = "Unable to join game. The host's address is invalid.";
        [FieldAttr(nst: 832, ctr: 864)] public string? _unableToJoinInvalidSession = "Unable to join game. The host's session is invalid.";
        [FieldAttr(nst: 840, ctr: 872)] public string? _unableToJoinIncompatibleSession = "Unable to join game. The host's session is incompatible.";
        [FieldAttr(nst: 848, ctr: 880)] public string? _unableToJoinTooManyLocalPlayers = "Unable to join game. You have too many local players.";
        [FieldAttr(nst: 856, ctr: 888)] public string? _unableToJoinEstablishingParty = "Unable to join game. Local session is still initializing. Try again later.";
        [FieldAttr(nst: 864, ctr: 896)] public string? _unableToJoinSessionDetailsNotFound = "Unable to join game. Session details not found.";
        [FieldAttr(nst: 872, ctr: 904)] public string? _unableToJoinSessionStillActive = "Unable to join game. Your session is still active.";
        [FieldAttr(nst: 880, ctr: 912)] public string? _unableToJoinFailedToCreateConnection = "Unable to join game. Failed to create connection.";
        [FieldAttr(nst: 888, ctr: 920)] public string? _unableToJoinFailedToCreateSession = "Unable to join game. Failed to create session.";
        [FieldAttr(nst: 896, ctr: 928)] public string? _unableToJoinFailedToRetrieveFriendInfo = "Unable to join game. Failed to retrieve friend information.";
        [FieldAttr(nst: 904, ctr: 936)] public string? _unableToJoinFailedToRetrieveInviteInfo = "Unable to join game. Failed to retrieve invitation data.";
        [FieldAttr(nst: 912, ctr: 944)] public string? _unableToJoinFailedToRetrieveSessionInfo = "Unable to join game. Failed to retrieve session.";
        [FieldAttr(nst: 920, ctr: 952)] public string? _unableToJoinTimedOutWaitingForLobby = "Unable to join game. Server connection timed out.";
        [FieldAttr(nst: 928, ctr: 960)] public string? _unableToJoinTimedOutWaitingForNatTraversal = "Unable to join game. NAT traversal timed out.";
        [FieldAttr(nst: 936, ctr: 968)] public string? _unableToJoinNoResults = "Unable to join game. The host's session is not advertised.";
        [FieldAttr(nst: 944, ctr: 976)] public string? _unableToJoinInvalidResults = "Unable to join game. The server did not return a matching session.";
        [FieldAttr(nst: 952, ctr: 984)] public string? _unableToJoinFailedToConnect = "Unable to join game. Failed to connect.";
        [FieldAttr(nst: 960, ctr: 992)] public string? _unableToJoinIncompatibleNatsLocalStrictRemoteStrict = "Unable to join game. Incompatible NAT types local strict and remote strict.";
        [FieldAttr(nst: 968, ctr: 1000)] public string? _unableToJoinIncompatibleNatsLocalStrictRemoteModerate = "Unable to join game. Incompatible NAT types local strict and remote moderate.";
        [FieldAttr(nst: 976, ctr: 1008)] public string? _unableToJoinIncompatibleNatsLocalModerateRemoteStrict = "Unable to join game. Incompatible NAT types local moderate and remote strict.";
        [FieldAttr(nst: 984, ctr: 1016)] public string? _unableToJoinFailedToSendJoinRequest = "Unable to join game. Failed to send join request.";
        [FieldAttr(nst: 992, ctr: 1024)] public string? _unableToJoinFailedToSendJoinReply = "Unable to join game. Failed to send join reply.";
        [FieldAttr(nst: 1000, ctr: 1032)] public string? _unableToJoinFailedToSendJoinCommit = "Unable to join game. Failed to send join commit.";
        [FieldAttr(nst: 1008, ctr: 1040)] public string? _unableToJoinFailedToSendJoinCommitReply = "Unable to join game. Failed to send join commit reply.";
        [FieldAttr(nst: 1016, ctr: 1048)] public string? _unableToJoinEndpointIdMismatch = "Unable to join game. Endpoint identifier mismatch.";
        [FieldAttr(nst: 1024, ctr: 1056)] public string? _unableToJoinFailedJoinCommit = "Unable to join game. Failed to commit join.";
        [FieldAttr(nst: 1032, ctr: 1064)] public string? _unableToJoinNotFriends = "Unable to join game. You must be friends to play online.";
        [FieldAttr(nst: 1040, ctr: 1072)] public string? _unableToJoinGameNotInstalled = "Unable to join game. The host's game is not fully installed.";
        [FieldAttr(ctr: 1080)] public string? _unableToJoinGameActiveUser;
        [FieldAttr(nst: 1048, ctr: 1088)] public string? _genericTRCNetworkError = "Network unavailable. Please try again.";
        [FieldAttr(nst: 1056, ctr: 1096)] public string? _downloadingText = "Downloading...";
        [FieldAttr(nst: 1064, ctr: 1104)] public string? _friendsText = "FRIENDS";
        [FieldAttr(nst: 1072, ctr: 1112)] public string? _onlinePlayRestricted = "Online play restricted.";
        [FieldAttr(nst: 1080, ctr: 1120)] public string? _patchRequired = "Patch available. You must update the application to use network features.";
        [FieldAttr(nst: 1088, ctr: 1128)] public string? _contentViewingRestricted = "Access to user generated content has been restricted.";
        [FieldAttr(nst: 1096, ctr: 1136)] public string? _viewLeaderboard = "Leaderboard";
        [FieldAttr(nst: 1104, ctr: 1144)] public string? _continueStoryToUnlock = "Continue the story to unlock soon.";
        [FieldAttr(nst: 1112, ctr: 1152)] public string? _checkpointString = "Checkpoint.";
        [FieldAttr(nst: 1120, ctr: 1160)] public string? _beginningString = "Beginning";
        [FieldAttr(nst: 1128, ctr: 1168)] public string? _copyrightString = null;
        [FieldAttr(nst: 1136, ctr: 1176)] public string? _autosaveString = null;
        [FieldAttr(nst: 1144, ctr: 1184)] public string? _titleScreenPressStartString = "PRESS START";
        [FieldAttr(nst: 1152, ctr: 1192)] public string? _titleScreenTapToStartString = "TAP TO START";
        [FieldAttr(nst: 1160)] public string? _titleScreenClickToStartString = "CLICK TO START";
        [FieldAttr(nst: 1168, ctr: 1200)] public string? _hudPressStartString = "PRESS START";
        [FieldAttr(nst: 1176, ctr: 1208)] public string? _dialogBoxUnavailableContentTitle = "UNAVAILABLE";
        [FieldAttr(nst: 1184, ctr: 1216)] public string? _areaNotYetInstalledWarning = "This area has not been fully installed. You will be returned to the main menu.";
        [FieldAttr(nst: 1192, ctr: 1224)] public string? _onlineUnavailableWarning = "The game must be fully installed to access online features.";
        [FieldAttr(nst: 1200, ctr: 1232)] public string? _ownerString = "%s's";
        [FieldAttr(nst: 1208, ctr: 1240)] public string? _colonFormatString = "%s";
        [FieldAttr(nst: 1216, ctr: 1248)] public string? _gamertagString = "NAME";
        [FieldAttr(nst: 1224, ctr: 1256)] public string? _installingTrophyString = "";
        [FieldAttr(nst: 1232, ctr: 1264)] public string? _reinstallingTrophyString = "";
        [FieldAttr(nst: 1240, ctr: 1272)] public string? _questInteractionDescription = "Talk to %s";
        [FieldAttr(nst: 1248, ctr: 1280)] public string? _notInHubQuestInteractionDescription = "Talk to %s in %s";
        [FieldAttr(nst: 1256, ctr: 1288)] public string? _inviteMessage = "Let's play Skylanders SuperChargers online!";
        [FieldAttr(nst: 1264, ctr: 1296)] public string? _inviteSendingText = "Sending invite...";
        [FieldAttr(nst: 1272, ctr: 1304)] public string? _inviteSuccessText = "Invite sent";
        [FieldAttr(nst: 1280, ctr: 1312)] public string? _inviteFailureText = "Failed to send invite";
        [FieldAttr(nst: 1288, ctr: 1320)] public string? _onlineJoiningDialogTitle = "Please Wait";
        [FieldAttr(nst: 1296, ctr: 1328)] public string? _onlineJoiningDialogBody = "Joining game...";
        [FieldAttr(nst: 1304, ctr: 1336)] public string? _onlineMultiplayerRestrictedMessage = "Online multiplayer is not permitted for your account.";
        [FieldAttr(nst: 1312, ctr: 1344)] public string? _onlineMultiplayerOverCellularMessage = "Online multiplayer is not supported on cellular network.";
        [FieldAttr(nst: 1320, ctr: 1352)] public string? _onlinePlayDisabledMessage = "Skylander SuperChargers servers are offline.";
        [FieldAttr(nst: 1328, ctr: 1360)] public string? _contentDeploymentDownloadTitle = "Downloading Content";
        [FieldAttr(nst: 1336, ctr: 1368)] public string? _contentDeploymentDownloadMessage = "Download\n%.2f %% complete.";
        [FieldAttr(nst: 1344, ctr: 1376)] public string? _contentDeploymentDownloadStartingTitle = "Preparing Download";
        [FieldAttr(nst: 1352, ctr: 1384)] public string? _contentDeploymentDownloadStartingMessage = "Connecting to download servers.";
        [FieldAttr(nst: 1360, ctr: 1392)] public string? _contentDeploymentErrorTitle = "Download Error";
        [FieldAttr(nst: 1368, ctr: 1400)] public string? _contentDeploymentErrorMessage = "Please check your internet connection and try again. (Error";
        [FieldAttr(nst: 1376, ctr: 1408)] public string? _wifiConnectionRequiredTitle = "Network Error";
        [FieldAttr(nst: 1384, ctr: 1416)] public string? _wifiConnectionRequiredMessage = "Wi-Fi required to download game content. (Error";
        [FieldAttr(nst: 1392, ctr: 1424)] public string? _contentDeploymentValidatingTitle = "Validating Content";
        [FieldAttr(nst: 1400, ctr: 1432)] public string? _contentDeploymentValidatingMessage = "Validation %.2f %% complete";
        [FieldAttr(nst: 1408, ctr: 1440)] public string? _contentDeploymentReservingTitle = "Reserving Cache Space";
        [FieldAttr(nst: 1416, ctr: 1448)] public string? _contentDeploymentReservingMessage = "Reserve %.2f %% complete";
        [FieldAttr(nst: 1424, ctr: 1456)] public string? _contentDeploymentOutOfDiskSpaceTitle = "Out of Storage";
        [FieldAttr(nst: 1432, ctr: 1464)] public string? _contentDeploymentOutOfDiskSpaceMessage = "%llu more MB of storage\nrequired to install game";
        [FieldAttr(nst: 1440, ctr: 1472)] public string? _contentDeploymentNeedMoreSpaceMessage = "There is not enough available storage to download game content. Please free up storage.";
        [FieldAttr(nst: 1448, ctr: 1480)] public string? _contentDeploymentRetryOption = "Retry";
        [FieldAttr(nst: 1456, ctr: 1488)] public string? _contentDeploymentAbortOption = "Abort";
        [FieldAttr(nst: 1464, ctr: 1496)] public string? _newSaveOnlineMessage = "In Skylanders SuperChargers you can use Game Chat with other players on your friends list. Make sure to get permission from your parent or guardian before using chat or playing online. They can go to Skylanders.com/parents to learn how to adjust your chat and online settings and find out more about these new features. You can adjust your preferences for Online play through the Options screen in the Pause Menu.\nEnable Game Chat?";
        [FieldAttr(nst: 1472, ctr: 1504)] public string? _networkInitializationFailed = "Failed to initialize network, try again later";
        [FieldAttr(nst: 1480, ctr: 1512)] public string? _vehicleTutorialControlMenuString = "Control Menu";
        [FieldAttr(nst: 1488, ctr: 1520)] public string? _vehicleSeaTutorialTitle = "Sea Controls";
        [FieldAttr(nst: 1496, ctr: 1528)] public string? _vehicleSeaTutorialMessage = "Hold > to Accelerate\nHold A to Dive\nRelease A to Jump";
        [FieldAttr(nst: 1504, ctr: 1536)] public string? _vehicleAirTutorialTitle = "Sky Controls";
        [FieldAttr(nst: 1512, ctr: 1544)] public string? _vehicleAirTutorialMessage = "Hold > to Accelerate\nPress A to Barrel Roll\nInvert Flight Controls in the Controls Menu";
        [FieldAttr(nst: 1520, ctr: 1552)] public string? _vehicleCoopTutorialTitle = "Co-op Controls";
        [FieldAttr(nst: 1528, ctr: 1560)] public string? _vehicleCoopTutorialMessage = "One Player Drives\nThe Passenger Shoots\nHold [ to Switch Positions\nShooters can Collect with ^";
        [FieldAttr(nst: 1536, ctr: 1568)] public string? _durangoWrongUserMessage = "Unless you sign-in as %s, you must quit and return to the Main Menu. Are you sure you want to exit?";
        [FieldAttr(nst: 1544, ctr: 1576)] public string? _requiredUpdateTitle = "Update Required";
        [FieldAttr(nst: 1552, ctr: 1584)] public string? _requiredUpdateMessage = "You must update your game before continuing.";
        [FieldAttr(ctr: 1592)] public string? _undockedSplitscreenWarningTitle;
        [FieldAttr(ctr: 1600)] public string? _undockedSplitscreenWarningBody;
        [FieldAttr(ctr: 1608)] public string? _undockedSettingsWarningBody;
        [FieldAttr(nst: 1560, ctr: 1616)] public string? _useInstantTrophy = "Use Instant Trophy";
        [FieldAttr(nst: 1568, ctr: 1624)] public string? _crash1DisplayName = "Crash Bandicoot";
        [FieldAttr(nst: 1576, ctr: 1632)] public string? _crash2DisplayName = "Crash Bandicoot 2";
        [FieldAttr(nst: 1584, ctr: 1640)] public string? _crash3DisplayName = "Crash Bandicoot 3";
        [FieldAttr(nst: 1592, ctr: 1648)] public string? _firstLabel = "1ST";
        [FieldAttr(nst: 1600, ctr: 1656)] public string? _secondLabel = "2ND";
        [FieldAttr(nst: 1608, ctr: 1664)] public string? _thirdLabel = "3RD";
        [FieldAttr(nst: 1616)] public string? _remappingConfirmationTitle = "Confirm Remapping";
        [FieldAttr(nst: 1624)] public string? _remappingConfirmationQuestion = "Remap \"{0}\" to {1}?";
        [FieldAttr(nst: 1632)] public string? _remappingAlreadyMapped = "Already mapped to";
        [FieldAttr(nst: 1640)] public string? _graphicsMenuConfirmationTitle = "Applying Graphics Settings";
        [FieldAttr(nst: 1648)] public string? _graphicsMenuConfirmationBody = "Are you sure you want to apply the current graphics settings?";
        [FieldAttr(nst: 1656)] public string? _graphicsMenuRevertDisplayTitle = "Display Settings Changed";
        [FieldAttr(nst: 1664)] public string? _graphicsMenuRevertDisplayBody = "Would you like to keep these display settings?\n\nDisplay will automatically revert\nto previous settings in...";
        [FieldAttr(nst: 1672)] public string? _initialsEntryDialogBody = "Enter your initials to save along with your record.";
        [FieldAttr(nst: 1680)] public string? _kbMovementKeysName = "Movement Keys";
        [FieldAttr(nst: 1688)] public string? _kbmButtonsNoneString = "NONE";
        [FieldAttr(nst: 1696)] public string? _kbmButtonsLeftClickString = "LEFT CLICK";
        [FieldAttr(nst: 1704)] public string? _kbmButtonsRightClickString = "RIGHT CLICK";
        [FieldAttr(nst: 1712)] public string? _kbmButtonsMiddleClickString = "MIDDLE CLICK";
        [FieldAttr(nst: 1720)] public string? _kbmButtonsWheelUpString = "WHEEL UP";
        [FieldAttr(nst: 1728)] public string? _kbmButtonsWheelDownString = "WHEEL DOWN";
        [FieldAttr(nst: 1736)] public string? _graphicsWindowedText = "Windowed";
        [FieldAttr(nst: 1744)] public string? _graphicsFullscreenText = "Fullscreen";
        [FieldAttr(nst: 1752)] public string? _graphicsWindowedFullscreenText = "Windowed Fullscreen";
        [FieldAttr(nst: 1760)] public string? _graphicsOnText = "On";
        [FieldAttr(nst: 1768)] public string? _graphicsOffText = "Off";
        [FieldAttr(nst: 1776)] public string? _graphicsLowText = "Low";
        [FieldAttr(nst: 1784)] public string? _graphicsMediumText = "Medium";
        [FieldAttr(nst: 1792)] public string? _graphicsHighText = "High";
        [FieldAttr(nst: 1800)] public string? _graphicsUltraText = "Ultra";
        [FieldAttr(nst: 1808)] public string? _graphicsCustomText = "Custom";
        [FieldAttr(nst: 1816)] public string? _saveFileDeleteString = "Delete";
        [FieldAttr(ctr: 1672)] public string? _lapString;
        [FieldAttr(ctr: 1680)] public string? _storeNameString;
        [FieldAttr(ctr: 1688)] public string? _storeUnavailableString;
        [FieldAttr(ctr: 1696)] public string? _optionsPromptString;
        [FieldAttr(ctr: 1704)] public string? _cupScoreIncrementString;
        [FieldAttr(ctr: 1712)] public string? _cupPlayerPointsString;
        [FieldAttr(ctr: 1720)] public string? _easyDifficultyString;
        [FieldAttr(ctr: 1728)] public string? _mediumDifficultyString;
        [FieldAttr(ctr: 1736)] public string? _hardDifficultyString;
        [FieldAttr(ctr: 1744)] public string? _timerSecondsString;
        [FieldAttr(ctr: 1752)] public string? _timerMinutesSecondsString;
        [FieldAttr(ctr: 1760)] public string? _storeLoadingString;
        [FieldAttr(ctr: 1768)] public string? _storeSoldOutString;
        [FieldAttr(ctr: 1776)] public string? _natTypeStrictString;
        [FieldAttr(ctr: 1784)] public string? _natTypeModerateString;
        [FieldAttr(ctr: 1792)] public string? _natTypeOpenString;
        [FieldAttr(ctr: 1800)] public string? _natTypeUnknownString;
        [FieldAttr(ctr: 1808)] public string? _connectionTypeWiredString;
        [FieldAttr(ctr: 1816)] public string? _connectionTypeWirelessString;
        [FieldAttr(ctr: 1824)] public string? _connectionTypeUnkownString;
        [FieldAttr(ctr: 1832)] public string? _configDownloadTitle;
        [FieldAttr(ctr: 1840)] public string? _configDownloadBody;
        [FieldAttr(ctr: 1848)] public string? _allPlayersLeft;
        [FieldAttr(ctr: 1856)] public string? _dialogBoxPitStopPurchaseTitle;
        [FieldAttr(ctr: 1864)] public string? _dialogBoxPitStopPurchaseBody;
        [FieldAttr(ctr: 1872)] public string? _pitStopPurchaseStatusString;
        [FieldAttr(ctr: 1880)] public string? _pitStopCurrencyStatusString;
        [FieldAttr(ctr: 1888)] public string? _pitStopPrerequisiteStatusString;
        [FieldAttr(ctr: 1896)] public string? _pitStopDiscountStatusString;
        [FieldAttr(ctr: 1904)] public string? _pitStopAdventureStatusString;
        [FieldAttr(ctr: 1912)] public string? _matchmakingErrorTitle;
        [FieldAttr(ctr: 1920)] public string? _mmErrorPartyMemberDisconnected;
        [FieldAttr(ctr: 1928)] public string? _mmErrorHostMigrationFailed;
        [FieldAttr(ctr: 1936)] public string? _mmErrorSearchExpired;
        [FieldAttr(ctr: 1944)] public string? _mmErrorInternalError;
        [FieldAttr(ctr: 1952)] public string? _mmErrorActionAbort;
        [FieldAttr(ctr: 1960)] public string? _mmErrorActionRetry;
        [FieldAttr(ctr: 1968)] public string? _wumpaCoinsNotSignedInTitle;
        [FieldAttr(ctr: 1976)] public string? _wumpaCoinsNotSignedInBody;
        [FieldAttr(ctr: 1984)] public string? _pitstopUnavailableTitle;
        [FieldAttr(ctr: 1992)] public string? _pitstopUnavailableBody;
        [FieldAttr(ctr: 2000)] public string? _grandPrixUnavailableTitle;
        [FieldAttr(ctr: 2008)] public string? _grandPrixUnavailableBody;
        [FieldAttr(ctr: 2016)] public string? _grandPrixLoadingBody;
        [FieldAttr(ctr: 2024)] public string? _grandPrixLoadingTitle;
        [FieldAttr(ctr: 2032)] public string? _dialogBoxPitStopPurchaseBundleTitle;
        [FieldAttr(ctr: 2040)] public string? _dialogBoxPitStopPurchaseBundleBody;
        [FieldAttr(ctr: 2048)] public string? _pitStopPurchaseStatusBundleString;
        [FieldAttr(ctr: 2056)] public string? _pitStopCurrencyStatusBundleString;
        [FieldAttr(ctr: 2064)] public string? _pitStopDailyTimeRemainingString;
        [FieldAttr(ctr: 2072)] public string? _OnlineMultiplayerRestrictedContinueMessage;
        [FieldAttr(ctr: 2080)] public string? _pitStopNitroBoostString;
        [FieldAttr(ctr: 2088)] public string? _pitStopDiscountString;
        [FieldAttr(ctr: 2096)] public string? _cheatCodeAchievementsDisabled;
        [FieldAttr(ctr: 2104)] public string? _grandPrixDaysRemaining;
        [FieldAttr(ctr: 2112)] public string? _grandPrixOneDayRemaining;
        [FieldAttr(ctr: 2120)] public string? _grandPrixOffSeason;
        [FieldAttr(ctr: 2128)] public string? _grandPrixLeaderboardRewardString;
        [FieldAttr(ctr: 2136)] public string? _grandPrixLeaderboardTotalPlayerCount;
        [FieldAttr(ctr: 2144)] public string? _grandPrixResetMessage;
        [FieldAttr(ctr: 2152)] public string? _grandPrixOffSeasonMessage;
        [FieldAttr(ctr: 2160)] public string? _grandPrixRewardKartName;
        [FieldAttr(ctr: 2168)] public string? _grandPrixRewardDecalName;
        [FieldAttr(ctr: 2176)] public string? _pitStopGPCompleteTitle;
        [FieldAttr(ctr: 2184)] public string? _pitStopGPCompleteBody;
        [FieldAttr(ctr: 2192)] public string? _pitStopFillUpPopUpTitle;
        [FieldAttr(ctr: 2200)] public string? _pitStopFillUpPopUpBody;
        [FieldAttr(ctr: 2208)] public string? _noNetworkConnectionPopupTitle;
        [FieldAttr(ctr: 2216)] public string? _noNetworkConnectionPopupBody;
        [FieldAttr(ctr: 2224)] public string? _configFileDownloadedPopupBody;
    }
}
