namespace Alchemy
{
    [ObjectAttr(ctr: 632, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class Octane_Customization_Root : igGuiVscBehavior
    {
        [FieldAttr(ctr: 40)] public igHandleMetaField _Gui_Animation_Tag_0x28 = new();
        [FieldAttr(ctr: 48)] public igHandleMetaField _Gui_Placeable_0x30 = new();
        [FieldAttr(ctr: 56)] public bool _Bool_0x38;
        [FieldAttr(ctr: 64)] public igHandleMetaField _Gui_Animation_Tag_0x40 = new();
        [FieldAttr(ctr: 72)] public igHandleMetaField _Gui_Animation_Tag_0x48 = new();
        [FieldAttr(ctr: 80)] public igHandleMetaField _Gui_Animation_Tag_0x50 = new();
        [FieldAttr(ctr: 88)] public igHandleMetaField _Gui_Placeable_0x58 = new();
        [FieldAttr(ctr: 96)] public igHandleMetaField _Gui_Placeable_0x60 = new();
        [FieldAttr(ctr: 104)] public igHandleMetaField _Gui_Animation_Tag_0x68 = new();
        [FieldAttr(ctr: 112)] public igHandleMetaField _Gui_Animation_Tag_0x70 = new();
        [FieldAttr(ctr: 120)] public igHandleMetaField _Gui_Animation_Tag_0x78 = new();
        [FieldAttr(ctr: 128)] public igHandleMetaField _Gui_Animation_Tag_0x80 = new();
        [FieldAttr(ctr: 136)] public igHandleMetaField _Gui_Animation_Tag_0x88 = new();
        [FieldAttr(ctr: 144)] public bool _Bool_0x90;
        [FieldAttr(ctr: 152)] public igHandleMetaField _Gui_Animation_Tag_0x98 = new();
        [FieldAttr(ctr: 160)] public igHandleMetaField _Gui_Placeable_0xa0 = new();
        [FieldAttr(ctr: 168)] public bool _Bool_0xa8;
        [FieldAttr(ctr: 176)] public igHandleMetaField _Gui_Animation_Tag_0xb0 = new();
        [FieldAttr(ctr: 184)] public igObject? _InternalStore__timer = new();
        [FieldAttr(ctr: 192)] public bool _Bool_0xc0;
        [FieldAttr(ctr: 200)] public igHandleMetaField _Gui_Animation_Tag_0xc8 = new();
        [FieldAttr(ctr: 208)] public igHandleMetaField _Localized_String_0xd0 = new();
        [FieldAttr(ctr: 216)] public igHandleMetaField _Localized_String_0xd8 = new();
        [FieldAttr(ctr: 224)] public bool _Bool_0xe0;
        [FieldAttr(ctr: 225)] public bool _Bool_0xe1;
        [FieldAttr(ctr: 232)] public string? _String = null;
        [FieldAttr(ctr: 240)] public EPlayerId _E_Player_Id;
        [FieldAttr(ctr: 248)] public igHandleMetaField _Entity_0xf8 = new();
        [FieldAttr(ctr: 256)] public bool _Bool_0x100;
        [FieldAttr(ctr: 264)] public igHandleMetaField _InternalStore_project = new();
        [FieldAttr(ctr: 272)] public igHandleMetaField _Entity_0x110 = new();
        [FieldAttr(ctr: 280)] public igHandleMetaField _Localized_String_0x118 = new();
        [FieldAttr(ctr: 288)] public igHandleMetaField _Localized_String_0x120 = new();
        [FieldAttr(ctr: 296)] public igHandleMetaField _Localized_String_0x128 = new();
        [FieldAttr(ctr: 304)] public igHandleMetaField _Localized_String_0x130 = new();
        [FieldAttr(ctr: 312)] public bool _Bool_0x138;
        [FieldAttr(ctr: 313)] public bool _Bool_0x139;
        [FieldAttr(ctr: 320)] public igHandleMetaField _Gui_Placeable_0x140 = new();
        [FieldAttr(ctr: 328)] public igHandleMetaField _Localized_String_0x148 = new();
        [FieldAttr(ctr: 336)] public igHandleMetaField _Gui_Animation_Tag_0x150 = new();
        [FieldAttr(ctr: 344)] public bool _Bool_0x158;
        [FieldAttr(ctr: 345)] public bool _Bool_0x159;
        [FieldAttr(ctr: 346)] public bool _Bool_0x15a;
        [FieldAttr(ctr: 352)] public igHandleMetaField _Zone_Info_0x160 = new();
        [FieldAttr(ctr: 360)] public igHandleMetaField _Zone_Info_0x168 = new();
        [FieldAttr(ctr: 368)] public bool _Bool_0x170;
        [FieldAttr(ctr: 369)] public bool _Bool_0x171;
        [FieldAttr(ctr: 370)] public bool _Bool_0x172;
        [FieldAttr(ctr: 371)] public bool _Bool_0x173;
        [FieldAttr(ctr: 376)] public igObject? _InternalStore_prioritySetHandler_0x178 = new();
        [FieldAttr(ctr: 384)] public igHandleMetaField _Priority_Dsp_Override_Set_0x180 = new();
        [FieldAttr(ctr: 392)] public igHandleMetaField _Game_Sound_Music_Settings_0x188 = new();
        [FieldAttr(ctr: 400)] public igHandleMetaField _Game_Bool_Variable_0x190 = new();
        [FieldAttr(ctr: 408)] public igHandleMetaField _Localized_String_0x198 = new();
        [FieldAttr(ctr: 416)] public ECustomizationType _Gui_List_Item_Populator_Customization_Grid_E_Customization_Type;
        [FieldAttr(ctr: 424)] public igHandleMetaField _Localized_String_0x1a8 = new();
        [FieldAttr(ctr: 432)] public bool _Bool_0x1b0;
        [FieldAttr(ctr: 440)] public igHandleMetaField _Localized_String_0x1b8 = new();
        [FieldAttr(ctr: 448)] public igHandleMetaField _Localized_String_0x1c0 = new();
        [FieldAttr(ctr: 456)] public bool _Bool_0x1c8;
        [FieldAttr(ctr: 457)] public bool _Bool_0x1c9;
        [FieldAttr(ctr: 458)] public bool _Bool_0x1ca;
        [FieldAttr(ctr: 464)] public igHandleMetaField _Gui_Project = new();
        [FieldAttr(ctr: 472)] public bool _Bool_0x1d8;
        [FieldAttr(ctr: 480)] public igHandleMetaField _Gui_Animation_Tag_0x1e0 = new();
        [FieldAttr(ctr: 488)] public igHandleMetaField _Localized_String_0x1e8 = new();
        [FieldAttr(ctr: 496)] public EOctaneRaceModes _E_Octane_Race_Modes;
        [FieldAttr(ctr: 504)] public igObject? _Localized_String_0x1f8 = new();
        [FieldAttr(ctr: 512)] public igHandleMetaField _Localized_String_0x200 = new();
        [FieldAttr(ctr: 520)] public bool _Bool_0x208;
        [FieldAttr(ctr: 528)] public igHandleMetaField _Gui_Animation_Tag_0x210 = new();
        [FieldAttr(ctr: 536)] public igHandleMetaField _Gui_Placeable_0x218 = new();
        [FieldAttr(ctr: 544)] public bool _Bool_0x220;
        [FieldAttr(ctr: 552)] public igHandleMetaField _Game_Sound_Music_Settings_0x228 = new();
        [FieldAttr(ctr: 560)] public igHandleMetaField _Game_Sound_Music_Settings_0x230 = new();
        [FieldAttr(ctr: 568)] public igHandleMetaField _Game_Sound_Music_Settings_0x238 = new();
        [FieldAttr(ctr: 576)] public igHandleMetaField _Game_Sound_Music_Settings_0x240 = new();
        [FieldAttr(ctr: 584)] public igHandleMetaField _Game_Sound_Music_Settings_0x248 = new();
        [FieldAttr(ctr: 592)] public igHandleMetaField _Game_Int_Variable = new();
        [FieldAttr(ctr: 600)] public igHandleMetaField _Game_Sound_Music_Settings_0x258 = new();
        [FieldAttr(ctr: 608)] public igHandleMetaField _Game_Bool_Variable_0x260 = new();
        [FieldAttr(ctr: 616)] public igHandleMetaField _Priority_Dsp_Override_Set_0x268 = new();
        [FieldAttr(ctr: 624)] public igObject? _InternalStore_prioritySetHandler_0x270 = new();
    }
}
