namespace Alchemy
{
    [ObjectAttr(nst: 912, align: 16)]
    public class CLandVehicleCamera : CCamera
    {
        [FieldAttr(nst: 416)] public float _vehicleFollowDistance = 700.0f;
        [FieldAttr(nst: 420)] public float _vehicleFollowHeight = 300.0f;
        [FieldAttr(nst: 424)] public float _vehicleLookAtHeight;
        [FieldAttr(nst: 428)] public bool _useSplinePitch;
        [FieldAttr(nst: 432)] public float _splinePitchOffset = 1000.0f;
        [FieldAttr(nst: 436)] public float _angleToStopFollowingVehicle = 90.0f;
        [FieldAttr(nst: 440)] public float _angleToStopLockingCamera = 90.0f;
        [FieldAttr(nst: 444)] public float _recenteringDampingFactor = 0.1f;
        [FieldAttr(nst: 448)] public float _recenteringFromVehicleDraggingCameraFactor;
        [FieldAttr(nst: 452)] public float _vehiclePitchDampingFactor = 0.2f;
        [FieldAttr(nst: 456)] public float _vehicleYawDampingFactor = 0.2f;
        [FieldAttr(nst: 460)] public float _fovDampingFactor = 0.1f;
        [FieldAttr(nst: 464)] public float _vehicleRollDampingFactor = 0.2f;
        [FieldAttr(nst: 468)] public float _averageUpDampingFactor = 0.025f;
        [FieldAttr(nst: 472)] public float _verticalDampingFactor = 0.3f;
        [FieldAttr(nst: 476)] public float _verticalLookDampingFactor = 0.1f;
        [FieldAttr(nst: 480)] public float _driftTimeToMaxAngle = 3.0f;
        [FieldAttr(nst: 484)] public float _addedAngleWhileDrifting = 45.0f;
        [FieldAttr(nst: 488)] public float _camDriftDampingFactor = 0.3f;
        [FieldAttr(nst: 492)] public float _minHorizontalVelocity = 4000.0f;
        [FieldAttr(nst: 496)] public float _maxHorizontalVelocity = 8000.0f;
        [FieldAttr(nst: 500)] public float _minVerticalVelocity = 1000.0f;
        [FieldAttr(nst: 504)] public float _maxVerticalVelocity = 3000.0f;
        [FieldAttr(nst: 508)] public float _horizontalVelocitySwitchDampingFactor = 0.2f;
        [FieldAttr(nst: 512)] public float _verticalVelocitySwitchDampingFactor = 0.2f;
        [FieldAttr(nst: 516)] public float _verticalAngleDampingFactor = 0.1f;
        [FieldAttr(nst: 520)] public float _verticalAngleApplicationFactor = 0.5f;
        [FieldAttr(nst: 524)] public float _horizontalVelocityDampingFactor = 0.2f;
        [FieldAttr(nst: 528)] public float _modelOverridePitchMultiplier = 0.5f;
        [FieldAttr(nst: 536)] public CVehicleCameraZoomCollision? _zoomCollision;
        [FieldAttr(nst: 544)] public CVehicleCameraPanCollision? _leftPanCollision;
        [FieldAttr(nst: 552)] public CVehicleCameraPanCollision? _rightPanCollision;
        [FieldAttr(nst: 560)] public bool _lockCameraWhileParked;
        [FieldAttr(nst: 564)] public float _parkedTimeBeforeCameraLock = 1.0f;
        [FieldAttr(nst: 568)] public float _maxSpeedAnglePitch = 14.0f;
        [FieldAttr(nst: 572)] public float _maxSpeedAddedFov = 10.0f;
        [FieldAttr(nst: 576)] public float _vehiclePitchDampingVelocity;
        [FieldAttr(nst: 580)] public float _vehicleYawDampingVelocity;
        [FieldAttr(nst: 584)] public float _vehicleYawCumulator;
        [FieldAttr(nst: 588)] public float _vehicleRollDampingVelocity;
        [FieldAttr(nst: 592)] public igVec3fMetaField _recenteringDampingVelocity = new();
        [FieldAttr(nst: 604)] public float _vehicleHeightDampingVelocity;
        [FieldAttr(nst: 608)] public igVec3fMetaField _previousDirectionFromVehicleToCameraXY = new();
        [FieldAttr(nst: 620)] public float _previousVehiclePitch;
        [FieldAttr(nst: 624)] public float _previousVehicleYaw;
        [FieldAttr(nst: 628)] public float _previousVehicleDampenedYaw;
        [FieldAttr(nst: 632)] public float _previousVehicleRoll;
        [FieldAttr(nst: 636)] public float _overrideFov = 1.39999998f;
        [FieldAttr(nst: 640)] public float _previousOverrideFov = 1.39999998f;
        [FieldAttr(nst: 644)] public float _fovDampingVelocity;
        [FieldAttr(nst: 648)] public EPlayerId _playerId = EPlayerId.EPLAYERID_NONE;
        [FieldAttr(nst: 652)] public igVec3fMetaField _averageVehicleUp = new();
        [FieldAttr(nst: 664)] public float _dampenedUpMove;
        [FieldAttr(nst: 668)] public float _upMoveDampingVelocity;
        [FieldAttr(nst: 672)] public igVec3fMetaField _upDampingVelocity = new();
        [FieldAttr(nst: 684)] public igVec3fMetaField _lastVehiclePos = new();
        [FieldAttr(nst: 696)] public float _lastTotalUpMove;
        [FieldAttr(nst: 700)] public float _dampenedHorizontalDirLookFactor;
        [FieldAttr(nst: 704)] public float _dampenedVerticalDirLookFactor;
        [FieldAttr(nst: 708)] public float _horizontalDirLookDampingVelocity;
        [FieldAttr(nst: 712)] public float _verticalDirLookDampingVelocity;
        [FieldAttr(nst: 716)] public float _dampenedVerticalAngle;
        [FieldAttr(nst: 720)] public float _verticalAngleDampingVelocity;
        [FieldAttr(nst: 724)] public igVec2fMetaField _lastHorizontalVelocity = new();
        [FieldAttr(nst: 732)] public igVec3fMetaField _dampenedHorizontalVelocity = new();
        [FieldAttr(nst: 744)] public igVec3fMetaField _horizontalVelocityDampingVelocity = new();
        [FieldAttr(nst: 756)] public float _dampenedVehicleVerticalAngle;
        [FieldAttr(nst: 760)] public float _vehicleVerticalAngleDampingVelocity;
        [FieldAttr(nst: 764)] public CTransformMetaField _transformWithoutModifiers = new();
        [FieldAttr(nst: 792)] public CTransformMetaField _previousCameraTransform = new();
        [FieldAttr(nst: 820)] public igVec3fMetaField _vehicleUpSmoothed = new();
        [FieldAttr(nst: 832)] public bool _useTargetPosition;
        [FieldAttr(nst: 836)] public float _currentVehicleFollowDistance;
        [FieldAttr(nst: 840)] public float _currentVehicleFollowHeight;
        [FieldAttr(nst: 844)] public float _currentVehicleLookatHeight;
        [FieldAttr(nst: 848)] public float _addedFovRadians;
        [FieldAttr(nst: 852)] public float _addedFollowDistance;
        [FieldAttr(nst: 856)] public float _addedFollowHeight;
        [FieldAttr(nst: 860)] public float _addedBoostFovRadians;
        [FieldAttr(nst: 864)] public float _addedBoostFollowDistance;
        [FieldAttr(nst: 868)] public float _addedBoostFollowHeight;
        [FieldAttr(nst: 872)] public float _lastDriftRotateAngle;
        [FieldAttr(nst: 876)] public float _lastDriftCurrentYaw;
        [FieldAttr(nst: 880)] public float _lastDriftRotateAngleVelocity;
        [FieldAttr(nst: 884)] public bool _wasDrifting;
        [FieldAttr(nst: 888)] public float _postDriftTimer = 1.0f;
        [FieldAttr(nst: 892)] public float _yawAddition;
        [FieldAttr(nst: 896)] public bool _zoomCollided;
        [FieldAttr(nst: 897)] public bool _leftPanCollided;
        [FieldAttr(nst: 898)] public bool _rightPanCollided;
        [FieldAttr(nst: 900)] public float _lastQuickDiveDeltaDepth;
        [FieldAttr(nst: 904)] public float _lastQuickDiveVelocity;
    }
}
