namespace Alchemy
{
    [ObjectAttr(nst: 328, ctr: 568, align: 8)]
    public class CSystemData : igSingleton
    {
        [FieldAttr(nst: 16, ctr: 16)] public CPlayerSystemData? _playerSystemData;
        [FieldAttr(nst: 24, ctr: 24)] public CGlobalTuningData? _globalTuningData;
        [FieldAttr(nst: 32, ctr: 32)] public CDamageData? _superdropDamage;
        [FieldAttr(nst: 40, ctr: 40)] public CCombatFxData? _combatFxData;
        [FieldAttr(nst: 48)] public igHandleMetaField _superchargeDamageNumberMaterial = new();
        [FieldAttr(nst: 56, ctr: 48)] public CDebugSystemData? _debugData;
        [FieldAttr(nst: 64, ctr: 56)] public CCollisionMaterialHandleList? _globalCollisionMaterials;
        [FieldAttr(nst: 72, ctr: 64)] public float _minimumWallAngle = 60.0f;
        [FieldAttr(nst: 76, ctr: 68)] public float _gravity = -384.0f;
        [FieldAttr(nst: 80, ctr: 72)] public bool _entityVolumeCullingEnabled = true;
        [FieldAttr(nst: 88, ctr: 80)] public CCharacterAttributeStringHashTable? _characterAttributeNames;
        [FieldAttr(nst: 96, ctr: 88)] public CVehicleStatStringHashTable? _vehicleStatNames;
        [FieldAttr(nst: 104)] public CModLocationStringHashTable? _modNames;
        [FieldAttr(nst: 112)] public CModLocationStringHashTable? _modNamesPlural;
        [FieldAttr(nst: 120, ctr: 96)] public igStringRefList? _teamFactionNames;
        [FieldAttr(nst: 128, ctr: 104)] public CPlatformControllerVfxTable? _interactionPlatformVfxData;
        [FieldAttr(nst: 136, ctr: 112)] public CPlatformControllerVfxTable? _interactionMashPlatformVfxData;
        [FieldAttr(nst: 144, ctr: 120)] public CPlatformControllerToAnalogStickVfxTable? _interactionAnalogStickDirectionPlatformVfxData;
        [FieldAttr(nst: 152)] public CQueryFilter? _lightCoreBlastTargetFilter;
        [FieldAttr(nst: 160)] public CDamageData? _lightCoreBlastDamage;
        [FieldAttr(nst: 168, ctr: 128)] public igStringRefList? _heroVolumeGroups;
        [FieldAttr(nst: 176, ctr: 136)] public float _muteFadeTime = 0.1f;
        [FieldAttr(nst: 184, ctr: 144)] public CFadeInPresetData? _defaultFadeIn;
        [FieldAttr(nst: 192)] public igEntity? _majorCollectibleReplacement;
        [FieldAttr(nst: 200, ctr: 152)] public CPlayerRespawnData? _respawnData;
        [FieldAttr(nst: 208, ctr: 160)] public CControllerVibrationDataPresetTable? _vibrationPresets;
        [FieldAttr(nst: 216)] public CMobileGameStatBoostTable? _mobileBuffs;
        [FieldAttr(nst: 224, ctr: 168)] public string? _coopRespawnButtonHint = "Hold %s to respawn your skylander near the other player.";
        [FieldAttr(nst: 232, ctr: 176)] public float _coopRespawnButtonHintDuration = 6.0f;
        [FieldAttr(nst: 236, ctr: 180)] public float _coopRespawnButtonPreHintDelay = 30.0f;
        [FieldAttr(nst: 240, ctr: 184)] public float _coopRespawnButtonHintTetherLimitDelay = 3.0f;
        [FieldAttr(nst: 244, ctr: 188)] public float _holdRespawnButtonTriggerTime = 1.0f;
        [FieldAttr(nst: 248, ctr: 192)] public EXBUTTON _coopRespawnButton = EXBUTTON.L1;
        [FieldAttr(nst: 256)] public string? _difficultyFormat = "Difficulty";
        [FieldAttr(nst: 264)] public igStringRefList? _difficultyStrings;
        [FieldAttr(nst: 272, ctr: 200)] public CCollectibleSystemData? _collectibleSystemData;
        [FieldAttr(nst: 280, ctr: 208)] public CNetworkVisualizationComponentData? _networkVisualizationComponent;
        [FieldAttr(nst: 288)] public CGameSoundMusicSettings? _defaultMusicSettings;
        [FieldAttr(nst: 296, ctr: 216)] public CVehicleSystemData? _vehicleSystemData;
        [FieldAttr(nst: 304, ctr: 224)] public CSaveSystemData? _saveSystemData;
        [FieldAttr(nst: 312, ctr: 232)] public CUIDebugMenuList? _debugMenus;
        [FieldAttr(nst: 320, ctr: 240)] public CSystemInitializerList? _systemInitializers;
        [FieldAttr(ctr: 248)] public CPowerUpData? _powerUpData;
        [FieldAttr(ctr: 256)] public CPowerStartData? _powerStartData;
        [FieldAttr(ctr: 264)] public CGlobalKartData? _globalKartData;
        [FieldAttr(ctr: 272)] public CKartCustomizationGlobalData? _kartCustomizationGlobalData;
        [FieldAttr(ctr: 280)] public CNetworkAutenticationLicenceList? _networkAuthenticationLicenseList;
        [FieldAttr(ctr: 288)] public COctaneGameModeFilterList? _raceModeLayersFilters;
        [FieldAttr(ctr: 296)] public COctanePlayerCountFilterList? _playerCountLayersFilters;
        [FieldAttr(ctr: 304)] public CRacerDriverDataList? _availableDrivers;
        [FieldAttr(ctr: 312)] public CRacerDriverDataList? _adventureModeOpponents;
        [FieldAttr(ctr: 320)] public CKartCustomizationPresetList? _legacyKartPresets;
        [FieldAttr(ctr: 328)] public CRacerCustomizationPresetList? _legacyDriverKartPresets;
        [FieldAttr(ctr: 336)] public CRacerKartDataList? _availableKarts;
        [FieldAttr(ctr: 344)] public CRacerLODSystemData? _racerLODData;
        [FieldAttr(ctr: 352)] public CDriverDifficultyClassDataHashTable? _driverDifficultyClassDataTable;
        [FieldAttr(ctr: 360)] public CRacerPodiumDataList? _podiumDrivers;
        [FieldAttr(ctr: 368)] public CLevelAdditionalPackagesHastTable? _requiredPackages;
        [FieldAttr(ctr: 376)] public CCupPositionPointsData? _cupPositionPointsData;
        [FieldAttr(ctr: 384)] public COctaneCupSelectDataListList? _cupData;
        [FieldAttr(ctr: 392)] public COctaneBattleModeDataList? _octaneBattleModeList;
        [FieldAttr(ctr: 400)] public COctaneHelpHintsDataListList? _hintsData;
        [FieldAttr(ctr: 408)] public CHubAdventureAreaRaceDataList? _adventureRacesData;
        [FieldAttr(ctr: 416)] public COctaneHubProgressionValues? _hubProgressionValues;
        [FieldAttr(ctr: 424)] public igIntList? _battleArenaLives;
        [FieldAttr(ctr: 432)] public igIntList? _battleArenaLimitPoints;
        [FieldAttr(ctr: 440)] public igIntList? _battleArenaPoints;
        [FieldAttr(ctr: 448)] public igIntList? _battleArenaTimesMinutes;
        [FieldAttr(ctr: 456)] public COctaneRaceModesDifficultySpecificIntHashTable? _wumpaRewardCounts;
        [FieldAttr(ctr: 464)] public COctaneRaceModesDifficultySpecificRangedFloatHashTable? _wumpaRewardRanges;
        [FieldAttr(ctr: 472)] public float _photoFinishWinDelta;
        [FieldAttr(ctr: 476)] public int _burtRubberRequirement;
        [FieldAttr(ctr: 480)] public uint _chainedDriftTarget;
        [FieldAttr(ctr: 484)] public uint _chainedDriftBoostWithAllBoostTarget;
        [FieldAttr(ctr: 488)] public float _timeAllowedBetweenDrift;
        [FieldAttr(ctr: 492)] public float _timeAllowedBetweenDriftBoostAndBoostPad;
        [FieldAttr(ctr: 496)] public int _maxTokenCount;
        [FieldAttr(ctr: 500)] public int _maxGemCount;
        [FieldAttr(ctr: 504)] public int _maxRelicCount;
        [FieldAttr(ctr: 508)] public int _maxPurpleTokenCount;
        [FieldAttr(ctr: 512)] public CZoneInfoHandleList? _nitrostalgiaTracks;
        [FieldAttr(ctr: 520)] public igHandleMetaField _superTurboPadsCheatBoost = new();
        [FieldAttr(ctr: 528)] public igStringIntHashTable? _wumpaCoinsHashTable;
        [FieldAttr(ctr: 536)] public CZoneInfoGrandPrixDataList? _gpMapData;
        [FieldAttr(ctr: 544)] public CGrandPrixCustomizationsNPMultiplierList? _npRewardMultipliers;
        [FieldAttr(ctr: 552)] public int _minimumTimeForWumpasBattleMode;
        [FieldAttr(ctr: 556)] public int _miniumLapCountForWumpasRaceMode;
        [FieldAttr(ctr: 560)] public COctaneThemeSystemData? _themeSystemData;
    }
}
