namespace Alchemy
{
    [ObjectAttr(nst: 1280, ctr: 1328, align: 16)]
    public class CVisualDataGroup : igObject
    {
        [FieldAttr(nst: 16, ctr: 12)] public bool _sunColorState;
        [FieldAttr(nst: 17, ctr: 13)] public bool _sunIntensityState;
        [FieldAttr(nst: 18, ctr: 14)] public bool _sunAnglesState;
        [FieldAttr(nst: 19, ctr: 15)] public bool _skyGradientIntensityState;
        [FieldAttr(nst: 20, ctr: 16)] public bool _skySunIntensityState;
        [FieldAttr(nst: 21, ctr: 17)] public bool _skySunSizeState;
        [FieldAttr(nst: 22, ctr: 18)] public bool _skySunAnglesState;
        [FieldAttr(nst: 23, ctr: 19)] public bool _skySunshaftColorState;
        [FieldAttr(nst: 24, ctr: 20)] public bool _skySunshaftDecayState;
        [FieldAttr(nst: 25, ctr: 21)] public bool _skySunshaftDensityState;
        [FieldAttr(nst: 26, ctr: 22)] public bool _skySunshaftIntensityState;
        [FieldAttr(nst: 27, ctr: 23)] public bool _skySunshaftFadeState;
        [FieldAttr(nst: 28, ctr: 24)] public bool _skyFadeState;
        [FieldAttr(nst: 29, ctr: 25)] public bool _skyFarBlendState;
        [FieldAttr(nst: 30, ctr: 26)] public bool _skyNearParallaxState;
        [FieldAttr(nst: 31, ctr: 27)] public bool _cloudsLightVerticalState;
        [FieldAttr(nst: 32, ctr: 28)] public bool _cloudsLightWrapState;
        [FieldAttr(nst: 33, ctr: 29)] public bool _cloudsLitScaleState;
        [FieldAttr(nst: 34, ctr: 30)] public bool _cloudsDarkScaleState;
        [FieldAttr(nst: 35, ctr: 31)] public bool _cloudsHighlightSizeState;
        [FieldAttr(nst: 36, ctr: 32)] public bool _cloudsHighlightStrengthState;
        [FieldAttr(nst: 37, ctr: 33)] public bool _cloudsHighlightColorState;
        [FieldAttr(nst: 38, ctr: 34)] public bool _cloudsShadowSizeState;
        [FieldAttr(nst: 39, ctr: 35)] public bool _cloudsShadowStrengthState;
        [FieldAttr(nst: 40, ctr: 36)] public bool _cloudsShadowColorState;
        [FieldAttr(nst: 41, ctr: 37)] public bool _cloudsHazeStrengthState;
        [FieldAttr(nst: 42, ctr: 38)] public bool _cloudFadingNearOffsetState;
        [FieldAttr(nst: 43, ctr: 39)] public bool _cloudFadingFarOffsetState;
        [FieldAttr(nst: 44, ctr: 40)] public bool _cloudFadingHeightOffsetState;
        [FieldAttr(nst: 45, ctr: 41)] public bool _shadowLocalInfluenceState;
        [FieldAttr(nst: 46, ctr: 42)] public bool _shadowRangeState;
        [FieldAttr(nst: 47, ctr: 43)] public bool _shadowFadeStartState;
        [FieldAttr(nst: 48, ctr: 44)] public bool _shadowBiasState;
        [FieldAttr(ctr: 45)] public bool _shadowMapScaleState;
        [FieldAttr(ctr: 46)] public bool _shadowMaxCascadesCountState;
        [FieldAttr(nst: 49, ctr: 47)] public bool _shadowSplitDistributionState;
        [FieldAttr(nst: 50, ctr: 48)] public bool _shadowFadeState;
        [FieldAttr(nst: 51, ctr: 49)] public bool _shadowJumpInfluenceState;
        [FieldAttr(nst: 52, ctr: 50)] public bool _mobileShadowRangeState;
        [FieldAttr(nst: 53, ctr: 51)] public bool _mobileShadowHeightOffsetState;
        [FieldAttr(nst: 54, ctr: 52)] public bool _mobileShadowFarPlaneState;
        [FieldAttr(nst: 55, ctr: 53)] public bool _ambientSpecularScaleState;
        [FieldAttr(nst: 56, ctr: 54)] public bool _ambientDiffuseScaleState;
        [FieldAttr(nst: 57, ctr: 55)] public bool _ambientBakeAmbientInfluenceState;
        [FieldAttr(nst: 58, ctr: 56)] public bool _ambientBakeDirectInfluenceState;
        [FieldAttr(nst: 59, ctr: 57)] public bool _bloomLuminanceCutoffState;
        [FieldAttr(nst: 60, ctr: 58)] public bool _bloomScaleState;
        [FieldAttr(nst: 61, ctr: 59)] public bool _cloudCoverScaleState;
        [FieldAttr(nst: 62, ctr: 60)] public bool _cloudCoverTileSizeState;
        [FieldAttr(nst: 63, ctr: 61)] public bool _cloudCoverSpeedState;
        [FieldAttr(nst: 64, ctr: 62)] public bool _cloudCoverDirectionState;
        [FieldAttr(nst: 65, ctr: 63)] public bool _fogStartState;
        [FieldAttr(nst: 66, ctr: 64)] public bool _fogDensityState;
        [FieldAttr(nst: 67, ctr: 65)] public bool _fogColorState;
        [FieldAttr(nst: 68, ctr: 66)] public bool _fogSunColorState;
        [FieldAttr(nst: 69, ctr: 67)] public bool _fogSunInfluenceState;
        [FieldAttr(nst: 70, ctr: 68)] public bool _fogFarSkyIntensityState;
        [FieldAttr(nst: 71, ctr: 69)] public bool _visibilityEntityRadiusState;
        [FieldAttr(nst: 72, ctr: 70)] public bool _visibilityEntityDistanceAboveState;
        [FieldAttr(nst: 73, ctr: 71)] public bool _visibilityEntityDistanceBelowState;
        [FieldAttr(nst: 74, ctr: 72)] public bool _visibilityEntityOffsetState;
        [FieldAttr(nst: 75, ctr: 73)] public bool _visibilityLightDistanceState;
        [FieldAttr(nst: 76, ctr: 74)] public bool _visibilityLightRangeState;
        [FieldAttr(nst: 77, ctr: 75)] public bool _visibilityDistanceCullVeryLowState;
        [FieldAttr(nst: 78, ctr: 76)] public bool _visibilityDistanceCullLowState;
        [FieldAttr(nst: 79, ctr: 77)] public bool _visibilityDistanceCullMediumState;
        [FieldAttr(nst: 80, ctr: 78)] public bool _visibilityDistanceCullHighState;
        [FieldAttr(nst: 81, ctr: 79)] public bool _visibilityDistanceCullFadeRangeState;
        [FieldAttr(nst: 82, ctr: 80)] public bool _visibilityVfxCullDistanceState;
        [FieldAttr(nst: 83, ctr: 81)] public bool _obscuredFadeState;
        [FieldAttr(nst: 84, ctr: 82)] public bool _lodShaderDistanceState;
        [FieldAttr(nst: 85, ctr: 83)] public bool _windGeneralStrengthState;
        [FieldAttr(nst: 86, ctr: 84)] public bool _windGustFrequencyState;
        [FieldAttr(nst: 87, ctr: 85)] public bool _windGustStrengthMinState;
        [FieldAttr(nst: 88, ctr: 86)] public bool _windGustStrengthMaxState;
        [FieldAttr(nst: 89, ctr: 87)] public bool _windGustDurationMinState;
        [FieldAttr(nst: 90, ctr: 88)] public bool _windGustDurationMaxState;
        [FieldAttr(nst: 91, ctr: 89)] public bool _vignetteStrengthState;
        [FieldAttr(nst: 92, ctr: 90)] public bool _vignetteMidpointState;
        [FieldAttr(nst: 93, ctr: 91)] public bool _vignetteWidthState;
        [FieldAttr(nst: 94, ctr: 92)] public bool _colorGlobalExposureState;
        [FieldAttr(nst: 95, ctr: 93)] public bool _colorGlobalHueState;
        [FieldAttr(nst: 96, ctr: 94)] public bool _colorGlobalSaturationState;
        [FieldAttr(nst: 97, ctr: 95)] public bool _colorGlobalBrightnessState;
        [FieldAttr(nst: 98, ctr: 96)] public bool _colorGlobalContrastState;
        [FieldAttr(nst: 99, ctr: 97)] public bool _colorGlobalTintState;
        [FieldAttr(nst: 100, ctr: 98)] public bool _colorSeparableHueRedsState;
        [FieldAttr(nst: 101, ctr: 99)] public bool _colorSeparableHueYellowsState;
        [FieldAttr(nst: 102, ctr: 100)] public bool _colorSeparableHueGreensState;
        [FieldAttr(nst: 103, ctr: 101)] public bool _colorSeparableHueCyansState;
        [FieldAttr(nst: 104, ctr: 102)] public bool _colorSeparableHueBluesState;
        [FieldAttr(nst: 105, ctr: 103)] public bool _colorSeparableHueMagentasState;
        [FieldAttr(nst: 106, ctr: 104)] public bool _colorSeparableSaturationRedsState;
        [FieldAttr(nst: 107, ctr: 105)] public bool _colorSeparableSaturationYellowsState;
        [FieldAttr(nst: 108, ctr: 106)] public bool _colorSeparableSaturationGreensState;
        [FieldAttr(nst: 109, ctr: 107)] public bool _colorSeparableSaturationCyansState;
        [FieldAttr(nst: 110, ctr: 108)] public bool _colorSeparableSaturationBluesState;
        [FieldAttr(nst: 111, ctr: 109)] public bool _colorSeparableSaturationMagentasState;
        [FieldAttr(nst: 112, ctr: 110)] public bool _toonFadeState;
        [FieldAttr(nst: 113, ctr: 111)] public bool _toonLineWidthState;
        [FieldAttr(nst: 114, ctr: 112)] public bool _defocusFadeState;
        [FieldAttr(nst: 115, ctr: 113)] public bool _defocusPlanesState;
        [FieldAttr(nst: 116, ctr: 114)] public bool _waterSimulationFadeState;
        [FieldAttr(nst: 117, ctr: 115)] public bool _vfxQualityState;
        [FieldAttr(ctr: 116)] public bool _screenSpaceReflectionsParamsState;
        [FieldAttr(ctr: 117)] public bool _screenSpaceReflectionsParams2State;
        [FieldAttr(nst: 118, ctr: 118)] public bool _blendAll;
        [FieldAttr(nst: 128, ctr: 128)] public igVec4fMetaField _sunColor = new();
        [FieldAttr(nst: 144, ctr: 144)] public float _sunIntensity = 1.0f;
        [FieldAttr(nst: 148, ctr: 148)] public igVec3fMetaField _sunAngles = new();
        [FieldAttr(nst: 160, ctr: 160)] public bool _skyGradientState;
        [FieldAttr(nst: 164, ctr: 164)] public igVfxRangedCurveMetaField _skyGradientRed = new();
        [FieldAttr(nst: 248, ctr: 248)] public igVfxRangedCurveMetaField _skyGradientGreen = new();
        [FieldAttr(nst: 332, ctr: 332)] public igVfxRangedCurveMetaField _skyGradientBlue = new();
        [FieldAttr(nst: 416, ctr: 416)] public float _skyGradientIntensity = 1.0f;
        [FieldAttr(nst: 420, ctr: 420)] public float _skySunIntensity = 10.0f;
        [FieldAttr(nst: 424, ctr: 424)] public float _skySunSize = 0.15f;
        [FieldAttr(nst: 428, ctr: 428)] public igVec3fMetaField _skySunAngles = new();
        [FieldAttr(nst: 448, ctr: 448)] public igVec4fMetaField _skySunshaftColor = new();
        [FieldAttr(nst: 464, ctr: 464)] public float _skySunshaftDecay = 0.98f;
        [FieldAttr(nst: 468, ctr: 468)] public float _skySunshaftDensity = 1.0f;
        [FieldAttr(nst: 472, ctr: 472)] public float _skySunshaftIntensity = 1.0f;
        [FieldAttr(nst: 476, ctr: 476)] public float _skySunshaftFade = 1.0f;
        [FieldAttr(nst: 480, ctr: 480)] public float _skyFade = 1.0f;
        [FieldAttr(nst: 496, ctr: 496)] public igVec4fMetaField _skyFarBlend = new();
        [FieldAttr(nst: 512, ctr: 512)] public float _skyNearParallax = 0.0625f;
        [FieldAttr(nst: 516, ctr: 516)] public float _cloudsLightVertical = 0.5f;
        [FieldAttr(nst: 520, ctr: 520)] public float _cloudsLightWrap = 0.6f;
        [FieldAttr(nst: 524, ctr: 524)] public float _cloudsLitScale = 1.14999998f;
        [FieldAttr(nst: 528, ctr: 528)] public float _cloudsDarkScale = 0.75f;
        [FieldAttr(nst: 532, ctr: 532)] public float _cloudsHighlightSize = 0.2f;
        [FieldAttr(nst: 536, ctr: 536)] public float _cloudsHighlightStrength = 0.2f;
        [FieldAttr(nst: 544, ctr: 544)] public igVec4fMetaField _cloudsHighlightColor = new();
        [FieldAttr(nst: 560, ctr: 560)] public float _cloudsShadowSize = 0.2f;
        [FieldAttr(nst: 564, ctr: 564)] public float _cloudsShadowStrength = 0.2f;
        [FieldAttr(nst: 576, ctr: 576)] public igVec4fMetaField _cloudsShadowColor = new();
        [FieldAttr(nst: 592, ctr: 592)] public float _cloudsHazeStrength = 1.0f;
        [FieldAttr(nst: 596, ctr: 596)] public float _cloudFadingNearOffset;
        [FieldAttr(nst: 600, ctr: 600)] public float _cloudFadingFarOffset;
        [FieldAttr(nst: 604, ctr: 604)] public float _cloudFadingHeightOffset = 64.0f;
        [FieldAttr(nst: 608, ctr: 608)] public float _shadowLocalInfluence;
        [FieldAttr(nst: 612, ctr: 612)] public float _shadowRange = 3000.0f;
        [FieldAttr(nst: 616, ctr: 616)] public float _shadowFadeStart = 15000.0f;
        [FieldAttr(nst: 624, ctr: 624)] public igVec4fMetaField _shadowBias = new();
        [FieldAttr(ctr: 640)] public float _shadowMapScale;
        [FieldAttr(ctr: 644)] public float _shadowMaxCascadesCount;
        [FieldAttr(nst: 640, ctr: 648)] public float _shadowSplitDistribution = 0.89999998f;
        [FieldAttr(nst: 644, ctr: 652)] public float _shadowFade = 1.0f;
        [FieldAttr(nst: 648, ctr: 656)] public float _shadowJumpInfluence = 1.0f;
        [FieldAttr(nst: 652, ctr: 660)] public float _mobileShadowRange = 1000.0f;
        [FieldAttr(nst: 656, ctr: 664)] public float _mobileShadowHeightOffset = 1000.0f;
        [FieldAttr(nst: 660, ctr: 668)] public float _mobileShadowFarPlane = 1500.0f;
        [FieldAttr(nst: 664, ctr: 672)] public float _ambientSpecularScale = 1.0f;
        [FieldAttr(nst: 668, ctr: 676)] public float _ambientDiffuseScale = 1.0f;
        [FieldAttr(nst: 672, ctr: 680)] public bool _ambientDiffuseColorState;
        [FieldAttr(nst: 676, ctr: 684)] public igVfxRangedCurveMetaField _ambientDiffuseColorRed = new();
        [FieldAttr(nst: 760, ctr: 768)] public igVfxRangedCurveMetaField _ambientDiffuseColorGreen = new();
        [FieldAttr(nst: 844, ctr: 852)] public igVfxRangedCurveMetaField _ambientDiffuseColorBlue = new();
        [FieldAttr(nst: 928, ctr: 936)] public bool _ambientAtmosphereEffectState;
        [FieldAttr(nst: 936, ctr: 944)] public igHandleMetaField _ambientAtmosphereEffect = new();
        [FieldAttr(nst: 944, ctr: 952)] public float _ambientBakeAmbientInfluence = 0.5f;
        [FieldAttr(nst: 948, ctr: 956)] public float _ambientBakeDirectInfluence = 1.0f;
        [FieldAttr(nst: 952, ctr: 960)] public float _bloomLuminanceCutoff = 5.0f;
        [FieldAttr(nst: 956, ctr: 964)] public float _bloomScale = 1.0f;
        [FieldAttr(nst: 960, ctr: 968)] public float _cloudCoverScale;
        [FieldAttr(nst: 964, ctr: 972)] public float _cloudCoverTileSize = 1.0f;
        [FieldAttr(nst: 968, ctr: 976)] public float _cloudCoverSpeed = 30.0f;
        [FieldAttr(nst: 972, ctr: 980)] public igVec2fMetaField _cloudCoverDirection = new();
        [FieldAttr(nst: 980, ctr: 988)] public float _fogStart;
        [FieldAttr(nst: 984, ctr: 992)] public float _fogDensity = 0.001f;
        [FieldAttr(nst: 992, ctr: 1008)] public igVec4fMetaField _fogColor = new();
        [FieldAttr(nst: 1008, ctr: 1024)] public igVec4fMetaField _fogSunColor = new();
        [FieldAttr(nst: 1024, ctr: 1040)] public float _fogSunInfluence = 100.0f;
        [FieldAttr(nst: 1028, ctr: 1044)] public float _fogFarSkyIntensity = 50.0f;
        [FieldAttr(nst: 1032, ctr: 1048)] public float _visibilityEntityRadius = 1800.0f;
        [FieldAttr(nst: 1036, ctr: 1052)] public float _visibilityEntityDistanceAbove = 900.0f;
        [FieldAttr(nst: 1040, ctr: 1056)] public float _visibilityEntityDistanceBelow = 900.0f;
        [FieldAttr(nst: 1044, ctr: 1060)] public float _visibilityEntityOffset = 900.0f;
        [FieldAttr(nst: 1048, ctr: 1064)] public float _visibilityLightDistance = 3700.0f;
        [FieldAttr(nst: 1052, ctr: 1068)] public float _visibilityLightRange = 300.0f;
        [FieldAttr(nst: 1056, ctr: 1072)] public float _visibilityDistanceCullVeryLow = 4000.0f;
        [FieldAttr(nst: 1060, ctr: 1076)] public float _visibilityDistanceCullLow = 8000.0f;
        [FieldAttr(nst: 1064, ctr: 1080)] public float _visibilityDistanceCullMedium = 16000.0f;
        [FieldAttr(nst: 1068, ctr: 1084)] public float _visibilityDistanceCullHigh = 24000.0f;
        [FieldAttr(nst: 1072, ctr: 1088)] public float _visibilityDistanceCullFadeRange = 500.0f;
        [FieldAttr(nst: 1076, ctr: 1092)] public float _visibilityVfxCullDistance = 6000.0f;
        [FieldAttr(nst: 1080, ctr: 1096)] public float _obscuredFade = 0.25f;
        [FieldAttr(nst: 1084, ctr: 1100)] public float _lodShaderDistance = 1200.0f;
        [FieldAttr(nst: 1088, ctr: 1104)] public float _windGeneralStrength = 0.25f;
        [FieldAttr(nst: 1092, ctr: 1108)] public float _windGustFrequency = 0.1f;
        [FieldAttr(nst: 1096, ctr: 1112)] public float _windGustStrengthMin;
        [FieldAttr(nst: 1100, ctr: 1116)] public float _windGustStrengthMax = 0.6f;
        [FieldAttr(nst: 1104, ctr: 1120)] public float _windGustDurationMin = 1.0f;
        [FieldAttr(nst: 1108, ctr: 1124)] public float _windGustDurationMax = 3.0f;
        [FieldAttr(nst: 1112, ctr: 1128)] public float _vignetteStrength;
        [FieldAttr(nst: 1116, ctr: 1132)] public float _vignetteMidpoint = 1.0f;
        [FieldAttr(nst: 1120, ctr: 1136)] public float _vignetteWidth = 0.5f;
        [FieldAttr(nst: 1124, ctr: 1140)] public float _colorGlobalExposure;
        [FieldAttr(nst: 1128, ctr: 1144)] public float _colorGlobalHue;
        [FieldAttr(nst: 1132, ctr: 1148)] public float _colorGlobalSaturation;
        [FieldAttr(nst: 1136, ctr: 1152)] public float _colorGlobalBrightness;
        [FieldAttr(nst: 1140, ctr: 1156)] public float _colorGlobalContrast;
        [FieldAttr(nst: 1152, ctr: 1168)] public igVec4fMetaField _colorGlobalTint = new();
        [FieldAttr(nst: 1168, ctr: 1184)] public float _colorSeparableHueReds;
        [FieldAttr(nst: 1172, ctr: 1188)] public float _colorSeparableHueYellows;
        [FieldAttr(nst: 1176, ctr: 1192)] public float _colorSeparableHueGreens;
        [FieldAttr(nst: 1180, ctr: 1196)] public float _colorSeparableHueCyans;
        [FieldAttr(nst: 1184, ctr: 1200)] public float _colorSeparableHueBlues;
        [FieldAttr(nst: 1188, ctr: 1204)] public float _colorSeparableHueMagentas;
        [FieldAttr(nst: 1192, ctr: 1208)] public float _colorSeparableSaturationReds;
        [FieldAttr(nst: 1196, ctr: 1212)] public float _colorSeparableSaturationYellows;
        [FieldAttr(nst: 1200, ctr: 1216)] public float _colorSeparableSaturationGreens;
        [FieldAttr(nst: 1204, ctr: 1220)] public float _colorSeparableSaturationCyans;
        [FieldAttr(nst: 1208, ctr: 1224)] public float _colorSeparableSaturationBlues;
        [FieldAttr(nst: 1212, ctr: 1228)] public float _colorSeparableSaturationMagentas;
        [FieldAttr(nst: 1216, ctr: 1232)] public float _toonFade;
        [FieldAttr(nst: 1220, ctr: 1236)] public float _toonLineWidth = 1.5f;
        [FieldAttr(nst: 1224, ctr: 1240)] public float _defocusFade = 1.0f;
        [FieldAttr(nst: 1232, ctr: 1248)] public igVec4fMetaField _defocusPlanes = new();
        [FieldAttr(nst: 1248, ctr: 1264)] public float _waterSimulationFade = 1.0f;
        [FieldAttr(nst: 1252, ctr: 1268)] public float _vfxQuality = 1.0f;
        [FieldAttr(nst: 1256, ctr: 1272)] public igHandleMetaField _reflectionMarker = new();
        [FieldAttr(nst: 1264, ctr: 1280)] public igPlane? _reflectionPlane;
        [FieldAttr(ctr: 1296)] public igVec4fMetaField _screenSpaceReflectionsParams = new();
        [FieldAttr(ctr: 1312)] public igVec4fMetaField _screenSpaceReflectionsParams2 = new();
    }
}
