namespace Alchemy
{
    [ObjectAttr(nst: 1048, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class common_Crash_Leaderboards_Root : igGuiVscBehavior
    {
        [FieldAttr(nst: 40)] public bool _Bool_0x28;
        [FieldAttr(nst: 48)] public igHandleMetaField _Localized_String_0x30 = new();
        [FieldAttr(nst: 56)] public igHandleMetaField _Gui_Animation_Tag_0x38 = new();
        [FieldAttr(nst: 64)] public igObject? _InternalStore_listener_0x40 = new();
        [FieldAttr(nst: 72)] public bool _Bool_0x48;
        [FieldAttr(nst: 80)] public igHandleMetaField _Gui_Animation_Tag_0x50 = new();
        [FieldAttr(nst: 88)] public igHandleMetaField _InternalStore_project_0x58 = new();
        [FieldAttr(nst: 96)] public igHandleMetaField _InternalStore_project_0x60 = new();
        [FieldAttr(nst: 104)] public igHandleMetaField _InternalStore_project_0x68 = new();
        [FieldAttr(nst: 112)] public int _Int_0x70;
        [FieldAttr(nst: 120)] public igObject? _Time_Trial_Leaderboard_Data_List_0x78 = new();
        [FieldAttr(nst: 128)] public igObject? _Time_Trial_Leaderboard_Data_List_0x80 = new();
        [FieldAttr(nst: 136)] public igObject? _Time_Trial_Leaderboard_Data_List_0x88 = new();
        [FieldAttr(nst: 144)] public igObject? _Time_Trial_Leaderboard_Data_List_0x90 = new();
        [FieldAttr(nst: 152)] public igObject? _Time_Trial_Leaderboard_Data_List_0x98 = new();
        [FieldAttr(nst: 160)] public int _InternalStore__internalCounter_0xa0;
        [FieldAttr(nst: 168)] public igHandleMetaField _InternalStore_project_0xa8 = new();
        [FieldAttr(nst: 176)] public igHandleMetaField _InternalStore_project_0xb0 = new();
        [FieldAttr(nst: 184)] public igHandleMetaField _Localized_String_0xb8 = new();
        [FieldAttr(nst: 192)] public igHandleMetaField _Localized_String_0xc0 = new();
        [FieldAttr(nst: 200)] public string? _String_0xc8 = null;
        [FieldAttr(nst: 208)] public string? _String_0xd0 = null;
        [FieldAttr(nst: 216)] public igHandleMetaField _Localized_String_0xd8 = new();
        [FieldAttr(nst: 224)] public igHandleMetaField _Localized_String_0xe0 = new();
        [FieldAttr(nst: 232)] public string? _String_0xe8 = null;
        [FieldAttr(nst: 240)] public int _Int_0xf0;
        [FieldAttr(nst: 248)] public igHandleMetaField _Gui_Placeable_0xf8 = new();
        [FieldAttr(nst: 256)] public igHandleMetaField _InternalStore_project_0x100 = new();
        [FieldAttr(nst: 264)] public bool _Bool_0x108;
        [FieldAttr(nst: 265)] public bool _Bool_0x109;
        [FieldAttr(nst: 266)] public bool _Bool_0x10a;
        [FieldAttr(nst: 272)] public igHandleMetaField _InternalStore_project_0x110 = new();
        [FieldAttr(nst: 280)] public igHandleMetaField _InternalStore_project_0x118 = new();
        [FieldAttr(nst: 288)] public igHandleMetaField _InternalStore_project_0x120 = new();
        [FieldAttr(nst: 296)] public igHandleMetaField _InternalStore_project_0x128 = new();
        [FieldAttr(nst: 304)] public igHandleMetaField _Gui_Animation_Tag_0x130 = new();
        [FieldAttr(nst: 312)] public igHandleMetaField _Gui_Placeable_0x138 = new();
        [FieldAttr(nst: 320)] public int _Int_0x140;
        [FieldAttr(nst: 324)] public int _Int_0x144;
        [FieldAttr(nst: 328)] public igHandleMetaField _Gui_Placeable_0x148 = new();
        [FieldAttr(nst: 336)] public int _Int_0x150;
        [FieldAttr(nst: 340)] public int _Int_0x154;
        [FieldAttr(nst: 344)] public igHandleMetaField _Gui_Placeable_0x158 = new();
        [FieldAttr(nst: 352)] public igHandleMetaField _Gui_Placeable_0x160 = new();
        [FieldAttr(nst: 360)] public int _Int_0x168;
        [FieldAttr(nst: 368)] public igHandleMetaField _Gui_Placeable_0x170 = new();
        [FieldAttr(nst: 376)] public igHandleMetaField _Gui_Placeable_0x178 = new();
        [FieldAttr(nst: 384)] public igHandleMetaField _Gui_Placeable_0x180 = new();
        [FieldAttr(nst: 392)] public igHandleMetaField _Gui_Placeable_id_l61tgmyl001 = new();
        [FieldAttr(nst: 400)] public igHandleMetaField _Gui_Shared_Asset_Project = new();
        [FieldAttr(nst: 408)] public igHandleMetaField _Gui_Placeable_0x198 = new();
        [FieldAttr(nst: 416)] public int _InternalStore__internalCounter_0x1a0;
        [FieldAttr(nst: 424)] public igObject? _Time_Trial_Leaderboard_Data_0x1a8 = new();
        [FieldAttr(nst: 432)] public igHandleMetaField _Gui_Animation_Tag_0x1b0 = new();
        [FieldAttr(nst: 440)] public int _InternalStore__internalCounter_0x1b8;
        [FieldAttr(nst: 448)] public igObject? _Time_Trial_Leaderboard_Data_0x1c0 = new();
        [FieldAttr(nst: 456)] public float _Float_0x1c8;
        [FieldAttr(nst: 460)] public float _Float_0x1cc;
        [FieldAttr(nst: 464)] public float _Float_0x1d0;
        [FieldAttr(nst: 468)] public float _Float_0x1d4;
        [FieldAttr(nst: 472)] public float _Float_0x1d8;
        [FieldAttr(nst: 476)] public igVec3fMetaField _Vector3 = new();
        [FieldAttr(nst: 488)] public float _Float_0x1e8;
        [FieldAttr(nst: 492)] public int _Int_0x1ec;
        [FieldAttr(nst: 496)] public igObject? _Gui_Placeable_List = new();
        [FieldAttr(nst: 504)] public igHandleMetaField _Gui_Placeable_0x1f8 = new();
        [FieldAttr(nst: 512)] public int _InternalStore__internalCounter_0x200;
        [FieldAttr(nst: 520)] public igHandleMetaField _Gui_Placeable_0x208 = new();
        [FieldAttr(nst: 528)] public int _Int_0x210;
        [FieldAttr(nst: 532)] public int _Int_0x214;
        [FieldAttr(nst: 536)] public int _Int_0x218;
        [FieldAttr(nst: 540)] public int _Int_0x21c;
        [FieldAttr(nst: 544)] public igHandleMetaField _Gui_Placeable_0x220 = new();
        [FieldAttr(nst: 552)] public igHandleMetaField _Gui_Placeable_0x228 = new();
        [FieldAttr(nst: 560)] public igHandleMetaField _Gui_Placeable_0x230 = new();
        [FieldAttr(nst: 568)] public igObject? _InternalStore_listener_0x238 = new();
        [FieldAttr(nst: 576)] public int _InternalStore__internalCounter_0x240;
        [FieldAttr(nst: 584)] public igHandleMetaField _Gui_Placeable_0x248 = new();
        [FieldAttr(nst: 592)] public igHandleMetaField _Gui_Placeable_0x250 = new();
        [FieldAttr(nst: 600)] public bool _Bool_0x258;
        [FieldAttr(nst: 604)] public int _Int_0x25c;
        [FieldAttr(nst: 608)] public int _Int_0x260;
        [FieldAttr(nst: 612)] public bool _Bool_0x264;
        [FieldAttr(nst: 616)] public igObject? _Time_Trial_Leaderboard_Data_0x268 = new();
        [FieldAttr(nst: 624)] public int _Int_0x270;
        [FieldAttr(nst: 628)] public int _Int_0x274;
        [FieldAttr(nst: 632)] public igHandleMetaField _Gui_Animation_Tag_0x278 = new();
        [FieldAttr(nst: 640)] public igHandleMetaField _Gui_Animation_Tag_0x280 = new();
        [FieldAttr(nst: 648)] public igHandleMetaField _Gui_Animation_Tag_0x288 = new();
        [FieldAttr(nst: 656)] public igHandleMetaField _Sound_0x290 = new();
        [FieldAttr(nst: 664)] public igHandleMetaField _Sound_0x298 = new();
        [FieldAttr(nst: 672)] public igHandleMetaField _Sound_0x2a0 = new();
        [FieldAttr(nst: 680)] public igHandleMetaField _Sound_0x2a8 = new();
        [FieldAttr(nst: 688)] public igHandleMetaField _Zone_Info = new();
        [FieldAttr(nst: 696)] public igHandleMetaField _Sound_0x2b8 = new();
        [FieldAttr(nst: 704)] public int _Int_0x2c0;
        [FieldAttr(nst: 708)] public int _Int_0x2c4;
        [FieldAttr(nst: 712)] public int _Int_0x2c8;
        [FieldAttr(nst: 720)] public igObject? _Time_Trial_Leaderboard_Data_List_0x2d0 = new();
        [FieldAttr(nst: 728)] public igHandleMetaField _Gui_Placeable_0x2d8 = new();
        [FieldAttr(nst: 736)] public int _Int_0x2e0;
        [FieldAttr(nst: 740)] public int _Int_0x2e4;
        [FieldAttr(nst: 744)] public igObject? _InternalStore_listener_0x2e8 = new();
        [FieldAttr(nst: 752)] public bool _Bool_0x2f0;
        [FieldAttr(nst: 760)] public igHandleMetaField _Gui_Animation_Tag_0x2f8 = new();
        [FieldAttr(nst: 768)] public igHandleMetaField _Gui_Animation_Tag_0x300 = new();
        [FieldAttr(nst: 776)] public igHandleMetaField _Localized_String_0x308 = new();
        [FieldAttr(nst: 784)] public igHandleMetaField _Sound_0x310 = new();
        [FieldAttr(nst: 792)] public igHandleMetaField _Game_Bool_Variable = new();
        [FieldAttr(nst: 800)] public bool _Bool_0x320;
        [FieldAttr(nst: 804)] public int _Int_0x324;
        [FieldAttr(nst: 808)] public int _Int_0x328;
        [FieldAttr(nst: 812)] public int _InternalStore__internalCounter_0x32c;
        [FieldAttr(nst: 816)] public igHandleMetaField _Gui_Placeable_0x330 = new();
        [FieldAttr(nst: 824)] public int _Int_0x338;
        [FieldAttr(nst: 832)] public igHandleMetaField _Gui_Placeable_0x340 = new();
        [FieldAttr(nst: 840)] public igHandleMetaField _Gui_Placeable_0x348 = new();
        [FieldAttr(nst: 848)] public igHandleMetaField _Gui_Placeable_0x350 = new();
        [FieldAttr(nst: 856)] public igHandleMetaField _Gui_Placeable_0x358 = new();
        [FieldAttr(nst: 864)] public igHandleMetaField _Gui_Placeable_0x360 = new();
        [FieldAttr(nst: 872)] public igHandleMetaField _Gui_Placeable_0x368 = new();
        [FieldAttr(nst: 880)] public igHandleMetaField _Gui_Placeable_0x370 = new();
        [FieldAttr(nst: 888)] public igHandleMetaField _Gui_Placeable_0x378 = new();
        [FieldAttr(nst: 896)] public igHandleMetaField _Gui_Placeable_0x380 = new();
        [FieldAttr(nst: 904)] public int _igIntMetaField334;
        [FieldAttr(nst: 908)] public int _igIntMetaField335;
        [FieldAttr(nst: 912)] public int _igIntMetaField336;
        [FieldAttr(nst: 916)] public int _igIntMetaField337;
        [FieldAttr(nst: 920)] public int _igIntMetaField338;
        [FieldAttr(nst: 928)] public string? _igStringMetaField339 = null;
        [FieldAttr(nst: 936)] public string? _igStringMetaField33a = null;
        [FieldAttr(nst: 944)] public string? _igStringMetaField33b = null;
        [FieldAttr(nst: 952)] public int _igIntMetaField3a9;
        [FieldAttr(nst: 956)] public int _igIntMetaField3aa;
        [FieldAttr(nst: 960)] public int _igIntMetaField3ab;
        [FieldAttr(nst: 964)] public int _igIntMetaField3ac;
        [FieldAttr(nst: 968)] public int _igIntMetaField3ad;
        [FieldAttr(nst: 976)] public string? _igStringMetaField3ae = null;
        [FieldAttr(nst: 984)] public string? _igStringMetaField3af = null;
        [FieldAttr(nst: 992)] public string? _igStringMetaField3b0 = null;
        [FieldAttr(nst: 1000)] public int _igIntMetaField41e;
        [FieldAttr(nst: 1004)] public int _igIntMetaField41f;
        [FieldAttr(nst: 1008)] public int _igIntMetaField420;
        [FieldAttr(nst: 1012)] public int _igIntMetaField421;
        [FieldAttr(nst: 1016)] public int _igIntMetaField422;
        [FieldAttr(nst: 1024)] public string? _igStringMetaField423 = null;
        [FieldAttr(nst: 1032)] public string? _igStringMetaField424 = null;
        [FieldAttr(nst: 1040)] public string? _igStringMetaField425 = null;
    }
}
