namespace Alchemy
{
    [ObjectAttr(nst: 712, align: 4, metaType: typeof(igGuiVscBehavior))]
    public class common_TimeTrial_Root : igGuiVscBehavior
    {
        [FieldAttr(nst: 40)] public igObject? _InternalStore_updateNodeUpdater = new();
        [FieldAttr(nst: 48)] public igObject? _InternalStore__counter = new();
        [FieldAttr(nst: 56)] public bool _Bool;
        [FieldAttr(nst: 64)] public igObject? _InternalStore__timer = new();
        [FieldAttr(nst: 72)] public igHandleMetaField _Gui_Placeable_0x48 = new();
        [FieldAttr(nst: 80)] public int _Int_0x50;
        [FieldAttr(nst: 84)] public int _Int_0x54;
        [FieldAttr(nst: 88)] public int _Int_0x58;
        [FieldAttr(nst: 92)] public float _Float_0x5c;
        [FieldAttr(nst: 96)] public igHandleMetaField _Gui_Placeable_0x60 = new();
        [FieldAttr(nst: 104)] public igHandleMetaField _Gui_Placeable_0x68 = new();
        [FieldAttr(nst: 112)] public igHandleMetaField _Gui_Placeable_0x70 = new();
        [FieldAttr(nst: 120)] public igHandleMetaField _Localized_String_0x78 = new();
        [FieldAttr(nst: 128)] public igHandleMetaField _Localized_String_0x80 = new();
        [FieldAttr(nst: 136)] public igHandleMetaField _Gui_Placeable_0x88 = new();
        [FieldAttr(nst: 144)] public igHandleMetaField _Gui_Placeable_0x90 = new();
        [FieldAttr(nst: 152)] public igHandleMetaField _Gui_Placeable_0x98 = new();
        [FieldAttr(nst: 160)] public igHandleMetaField _Localized_String_0xa0 = new();
        [FieldAttr(nst: 168)] public string? _String_0xa8 = null;
        [FieldAttr(nst: 176)] public igHandleMetaField _Gui_Animation_Tag_0xb0 = new();
        [FieldAttr(nst: 184)] public igHandleMetaField _Gui_Animation_Tag_0xb8 = new();
        [FieldAttr(nst: 192)] public igHandleMetaField _Gui_Animation_Tag_0xc0 = new();
        [FieldAttr(nst: 200)] public igHandleMetaField _Gui_Animation_Tag_0xc8 = new();
        [FieldAttr(nst: 208)] public igHandleMetaField _Gui_Animation_Tag_0xd0 = new();
        [FieldAttr(nst: 216)] public igObject? _InternalStore_listener = new();
        [FieldAttr(nst: 224)] public igHandleMetaField _Gui_Animation_Tag_0xe0 = new();
        [FieldAttr(nst: 232)] public igHandleMetaField _Gui_Placeable_0xe8 = new();
        [FieldAttr(nst: 240)] public igHandleMetaField _InternalStore_project = new();
        [FieldAttr(nst: 248)] public igHandleMetaField _Gui_Placeable_0xf8 = new();
        [FieldAttr(nst: 256)] public float _Float_0x100;
        [FieldAttr(nst: 260)] public float _Float_0x104;
        [FieldAttr(nst: 264)] public int _Int_0x108;
        [FieldAttr(nst: 272)] public igHandleMetaField _Gui_Animation_Tag_0x110 = new();
        [FieldAttr(nst: 280)] public igHandleMetaField _Localized_String_0x118 = new();
        [FieldAttr(nst: 288)] public igHandleMetaField _Gui_Animation_Tag_0x120 = new();
        [FieldAttr(nst: 296)] public igHandleMetaField _Gui_Animation_Tag_0x128 = new();
        [FieldAttr(nst: 304)] public int _InternalStore__internalCounter;
        [FieldAttr(nst: 312)] public igObject? _Localized_String_0x138 = new();
        [FieldAttr(nst: 320)] public igHandleMetaField _Localized_String_List = new();
        [FieldAttr(nst: 328)] public igHandleMetaField _Gui_Animation_Tag_0x148 = new();
        [FieldAttr(nst: 336)] public igHandleMetaField _Gui_Animation_Tag_0x150 = new();
        [FieldAttr(nst: 344)] public igHandleMetaField _Gui_Animation_Tag_0x158 = new();
        [FieldAttr(nst: 352)] public float _Float_0x160;
        [FieldAttr(nst: 360)] public igHandleMetaField _Zone_Info = new();
        [FieldAttr(nst: 368)] public float _Float_0x170;
        [FieldAttr(nst: 372)] public CTimeTrialNodes.ETimeTrialRelic _Time_Trial_Nodes_E_Time_Trial_Relic;
        [FieldAttr(nst: 376)] public igObject? _InternalStore__gate = new();
        [FieldAttr(nst: 384)] public igHandleMetaField _Open_Keyboard_Params = new();
        [FieldAttr(nst: 392)] public int _Int_0x188;
        [FieldAttr(nst: 396)] public int _Int_0x18c;
        [FieldAttr(nst: 400)] public int _Int_0x190;
        [FieldAttr(nst: 408)] public igHandleMetaField _Gui_Placeable_0x198 = new();
        [FieldAttr(nst: 416)] public igHandleMetaField _Gui_Placeable_0x1a0 = new();
        [FieldAttr(nst: 424)] public igHandleMetaField _Gui_Placeable_0x1a8 = new();
        [FieldAttr(nst: 432)] public int _Int_0x1b0;
        [FieldAttr(nst: 436)] public EZoneCollectibleType _E_Zone_Collectible_Type;
        [FieldAttr(nst: 440)] public igHandleMetaField _Entity = new();
        [FieldAttr(nst: 448)] public igHandleMetaField _Gui_Animation_Tag_0x1c0 = new();
        [FieldAttr(nst: 456)] public igHandleMetaField _Gui_Animation_Tag_0x1c8 = new();
        [FieldAttr(nst: 464)] public igHandleMetaField _Fade_Out_Preset_Data = new();
        [FieldAttr(nst: 472)] public igHandleMetaField _Bitmap_Font = new();
        [FieldAttr(nst: 480)] public string? _String_0x1e0 = null;
        [FieldAttr(nst: 488)] public igHandleMetaField _Game_String_Variable_0x1e8 = new();
        [FieldAttr(nst: 496)] public igHandleMetaField _Game_String_Variable_0x1f0 = new();
        [FieldAttr(nst: 504)] public igHandleMetaField _Character_Info_Hash_Table = new();
        [FieldAttr(nst: 512)] public string? _String_0x200 = null;
        [FieldAttr(nst: 520)] public int _igIntMetaField2e7;
        [FieldAttr(nst: 524)] public int _igIntMetaField2e8;
        [FieldAttr(nst: 528)] public int _igIntMetaField2e9;
        [FieldAttr(nst: 532)] public int _igIntMetaField2ea;
        [FieldAttr(nst: 536)] public int _igIntMetaField2eb;
        [FieldAttr(nst: 544)] public string? _igStringMetaField2ec = null;
        [FieldAttr(nst: 552)] public string? _igStringMetaField2ed = null;
        [FieldAttr(nst: 560)] public string? _igStringMetaField2ee = null;
        [FieldAttr(nst: 568)] public int _igIntMetaField35c;
        [FieldAttr(nst: 572)] public int _igIntMetaField35d;
        [FieldAttr(nst: 576)] public int _igIntMetaField35e;
        [FieldAttr(nst: 580)] public int _igIntMetaField35f;
        [FieldAttr(nst: 584)] public int _igIntMetaField360;
        [FieldAttr(nst: 592)] public string? _igStringMetaField361 = null;
        [FieldAttr(nst: 600)] public string? _igStringMetaField362 = null;
        [FieldAttr(nst: 608)] public string? _igStringMetaField363 = null;
        [FieldAttr(nst: 616)] public int _igIntMetaField3d1;
        [FieldAttr(nst: 620)] public int _igIntMetaField3d2;
        [FieldAttr(nst: 624)] public int _igIntMetaField3d3;
        [FieldAttr(nst: 628)] public int _igIntMetaField3d4;
        [FieldAttr(nst: 632)] public int _igIntMetaField3d5;
        [FieldAttr(nst: 640)] public string? _igStringMetaField3d6 = null;
        [FieldAttr(nst: 648)] public string? _igStringMetaField3d7 = null;
        [FieldAttr(nst: 656)] public string? _igStringMetaField3d8 = null;
        [FieldAttr(nst: 664)] public int _igIntMetaField446;
        [FieldAttr(nst: 668)] public int _igIntMetaField447;
        [FieldAttr(nst: 672)] public int _igIntMetaField448;
        [FieldAttr(nst: 676)] public int _igIntMetaField449;
        [FieldAttr(nst: 680)] public int _igIntMetaField44a;
        [FieldAttr(nst: 688)] public string? _igStringMetaField44b = null;
        [FieldAttr(nst: 696)] public string? _igStringMetaField44c = null;
        [FieldAttr(nst: 704)] public string? _igStringMetaField44d = null;
    }
}
