namespace Alchemy
{
    [ObjectAttr(nst: 1408, align: 16)]
    public class CAirVehicleCamera : CConstrainedCamera
    {
        [FieldAttr(nst: 432)] public float _followHeight = 600.0f;
        [FieldAttr(nst: 436)] public float _followDistance = 800.0f;
        [FieldAttr(nst: 440)] public float _lookAheadDistance = 400.0f;
        [FieldAttr(nst: 444)] public float _vehicleTurnRate = 100.0f;
        [FieldAttr(nst: 448)] public float _vehicleClimbRate = 2000.0f;
        [FieldAttr(nst: 452)] public float _followDistanceOnTurnModifier = -100.0f;
        [FieldAttr(nst: 456)] public float _safeAreaVerticalOffsetOnClimbModifier;
        [FieldAttr(nst: 460)] public float _safeAreaVerticalOffsetOnDescendModifier = 0.6f;
        [FieldAttr(nst: 464)] public float _safeAreaHorizontalOffsetOnTurnModifier = 1.0f;
        [FieldAttr(nst: 468)] public float _rotationDampingFactor = 20.0f;
        [FieldAttr(nst: 472)] public EigEaseType _turnDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(nst: 476)] public float _heightDampingFactor = 20.0f;
        [FieldAttr(nst: 480)] public EigEaseType _heightDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(nst: 484)] public float _screenSafeAreaOffsetDampingFactor = 20.0f;
        [FieldAttr(nst: 488)] public EigEaseType _screenSafeAreaOffsetDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(nst: 492)] public float _followDistanceDampingFactor = 20.0f;
        [FieldAttr(nst: 496)] public EigEaseType _followDistanceDampingEaseType = EigEaseType.kEaseTypeCubic;
        [FieldAttr(nst: 500)] public EPlayerId _playerId = EPlayerId.EPLAYERID_NONE;
        [FieldAttr(nst: 504)] public CCameraScreenSafeArea? _offsetScreenSafeArea;
        [FieldAttr(nst: 512)] public igVec3fMetaField _previousDirectionFromVehicleToCamera = new();
        [FieldAttr(nst: 524)] public igVec2fMetaField _previousScreenSafeAreaOffset = new();
        [FieldAttr(nst: 532)] public float _previousVehicleHeight;
        [FieldAttr(nst: 536)] public igVec3fMetaField _baseToMinimalSpeed = new();
        [FieldAttr(nst: 548)] public igVec3fMetaField _baseToMaximalSpeed = new();
        [FieldAttr(nst: 560)] public igVec3fMetaField _addTurnToMinimalSpeed = new();
        [FieldAttr(nst: 572)] public igVec3fMetaField _addTurnToMaximalSpeed = new();
        [FieldAttr(nst: 584)] public float _blendHorizontalFactor = 0.2f;
        [FieldAttr(nst: 588)] public float _blendVerticalFactor = 0.1f;
        [FieldAttr(nst: 592)] public float _blendTotalVelocityFactor = 0.2f;
        [FieldAttr(nst: 596)] public float _blendTurnFactor = 0.1f;
        [FieldAttr(nst: 600)] public float _maxTotalSpeed = 3000.0f;
        [FieldAttr(nst: 604)] public float _maxTurnRate = 100.0f;
        [FieldAttr(nst: 608)] public float _directionDampingFactor = 0.25f;
        [FieldAttr(nst: 612)] public bool _lookAtSupport;
        [FieldAttr(nst: 616)] public float _pitchAtMinimalSpeed;
        [FieldAttr(nst: 620)] public float _pitchAtMaximalSpeed;
        [FieldAttr(nst: 624)] public float _rearViewRelativeDistance = 0.61f;
        [FieldAttr(nst: 628)] public igVec3fMetaField _combatBaseToMinimalSpeed = new();
        [FieldAttr(nst: 640)] public igVec3fMetaField _combatBaseToMaximalSpeed = new();
        [FieldAttr(nst: 652)] public float _combatPitchAtMinimalSpeed;
        [FieldAttr(nst: 656)] public float _combatPitchAtMaximalSpeed;
        [FieldAttr(nst: 660)] public EXBUTTON _switchParametersButton = EXBUTTON.L3;
        [FieldAttr(nst: 664)] public float _switchTransitionSpeed = 1.5f;
        [FieldAttr(nst: 672)] public CVehicleCameraZoomCollision? _zoomCollision;
        [FieldAttr(nst: 680)] public CVehicleCameraPanCollision? _upPanCollision;
        [FieldAttr(nst: 688)] public igVec3fMetaField _directionDampingForwardVelocity = new();
        [FieldAttr(nst: 700)] public igVec3fMetaField _directionDampingUpVelocity = new();
        [FieldAttr(nst: 712)] public igVec3fMetaField _dampenedForward = new();
        [FieldAttr(nst: 724)] public igVec3fMetaField _dampenedUp = new();
        [FieldAttr(nst: 736)] public bool _previousTargetInit;
        [FieldAttr(nst: 740)] public float _currentSpeedRatio;
        [FieldAttr(nst: 744)] public float _previousTotalRatioVel;
        [FieldAttr(nst: 748)] public float _currentTurnRatio;
        [FieldAttr(nst: 752)] public float _previousTurnRatioVel;
        [FieldAttr(nst: 768)] public igMatrix44fMetaField _previousTargetTransform = new();
        [FieldAttr(nst: 832)] public CTransformMetaField _previousTransform = new();
        [FieldAttr(nst: 860)] public igVec3fMetaField _previousCameraTarget = new();
        [FieldAttr(nst: 872)] public igVec3fMetaField _previousCameraPositionVelocity = new();
        [FieldAttr(nst: 884)] public float _cameraPositionDampingFactor = 20.0f;
        [FieldAttr(nst: 888)] public igVec3fMetaField _previousCameraTargetVelocity = new();
        [FieldAttr(nst: 900)] public float _cameraTargetDampingFactor = 20.0f;
        [FieldAttr(nst: 904)] public float _previousVehicleCameraHeightOffset;
        [FieldAttr(nst: 908)] public float _previousVehicleCameraYawRotation;
        [FieldAttr(nst: 912)] public igVec2fMetaField _previousCameraPitchYaw = new();
        [FieldAttr(nst: 920)] public igVec2fMetaField _previousCameraPitchYawVelocity = new();
        [FieldAttr(nst: 928)] public float _previousCameraRoll;
        [FieldAttr(nst: 932)] public float _previousCameraRollVelocity;
        [FieldAttr(nst: 936)] public float _followPitchRatio = 0.75f;
        [FieldAttr(nst: 940)] public float _cameraPitchDampingFactor = 0.1f;
        [FieldAttr(nst: 944)] public float _cameraYawDampingFactor = 0.1f;
        [FieldAttr(nst: 948)] public float _cameraRollDampingFactor = 0.1f;
        [FieldAttr(nst: 952)] public float _verticalFollowAngle = 1.5f;
        [FieldAttr(nst: 956)] public float _followDistanceMax = 1000.0f;
        [FieldAttr(nst: 960)] public float _followDistanceMin = 600.0f;
        [FieldAttr(nst: 964)] public igVfxRangedCurveMetaField _followDistanceCurve = new();
        [FieldAttr(nst: 1048)] public float _rotationOffsetFromForward;
        [FieldAttr(nst: 1052)] public float _cameraRollMax = 8.0f;
        [FieldAttr(nst: 1056)] public float _cameraRollMin;
        [FieldAttr(nst: 1060)] public igVfxRangedCurveMetaField _cameraRollCurve = new();
        [FieldAttr(nst: 1144)] public float _cameraYawAngleWobble;
        [FieldAttr(nst: 1148)] public float _cameraYawMax;
        [FieldAttr(nst: 1152)] public float _cameraYawMin;
        [FieldAttr(nst: 1156)] public igVfxRangedCurveMetaField _cameraYawCurve = new();
        [FieldAttr(nst: 1240)] public bool _cameraAlwaysPitchAroundVehicle = true;
        [FieldAttr(nst: 1244)] public float _cameraPitchAngleWobble;
        [FieldAttr(nst: 1248)] public float _cameraPitchMax;
        [FieldAttr(nst: 1252)] public float _cameraPitchMin;
        [FieldAttr(nst: 1256)] public igVfxRangedCurveMetaField _cameraPitchCurve = new();
        [FieldAttr(nst: 1340)] public bool _cameraChecksForCollisions;
        [FieldAttr(nst: 1344)] public float _angleToStopFollowingVehicle = 90.0f;
        [FieldAttr(nst: 1348)] public float _angleToStopLockingCamera = 90.0f;
        [FieldAttr(nst: 1352)] public float _epicJumpFov = 100.0f;
        [FieldAttr(nst: 1356)] public float _addedBoostFovRadians;
        [FieldAttr(nst: 1360)] public bool _zoomCollided;
        [FieldAttr(nst: 1361)] public bool _upPanCollided;
        [FieldAttr(nst: 1362)] public bool _useCombatParameters;
        [FieldAttr(nst: 1364)] public igVec3fMetaField _currentBaseToMinimalSpeed = new();
        [FieldAttr(nst: 1376)] public igVec3fMetaField _currentBaseToMaximalSpeed = new();
        [FieldAttr(nst: 1388)] public float _currentPitchAtMinimalSpeed;
        [FieldAttr(nst: 1392)] public float _currentPitchAtMaximalSpeed;
    }
}
