namespace Alchemy
{
    [ObjectAttr(nst: 2944, align: 8)]
    public class CWaterVehicleComponentData : CBaseVehicleControllerComponentData
    {
        [FieldAttr(nst: 1776)] public float _buoyancy = 1.0f;
        [FieldAttr(nst: 1780)] public float _isolatedWaveBuoyancyMultiplier = 2.0f;
        [FieldAttr(nst: 1784)] public igVec3fMetaField _drag = new();
        [FieldAttr(nst: 1796)] public float _waterOffset;
        [FieldAttr(nst: 1800)] public float _enterWaterVelocityFactor = 0.8f;
        [FieldAttr(nst: 1804)] public float _exitWaterVelocityFactor = 0.8f;
        [FieldAttr(nst: 1808)] public float _enterWaterVelocityFactorRampLand = 0.5f;
        [FieldAttr(nst: 1812)] public float _enterWaterVelocityFactorRampDiveLand = 1.5f;
        [FieldAttr(nst: 1816)] public float _restingRatio = 0.5f;
        [FieldAttr(nst: 1820)] public float _restingOrientationStrength = 0.1f;
        [FieldAttr(nst: 1824)] public float _waveOrientationStrength = 0.1f;
        [FieldAttr(nst: 1828)] public float _rippleRadius = 75.0f;
        [FieldAttr(nst: 1832)] public float _rippleIntensity = 1.0f;
        [FieldAttr(nst: 1836)] public float _rippleReverseOffset = 300.0f;
        [FieldAttr(nst: 1840)] public float _rippleMinSpeed = 50.0f;
        [FieldAttr(nst: 1844)] public float _rippleMinAngularSpeed = 5.0f;
        [FieldAttr(nst: 1848)] public igRangedFloatMetaField _idleRippleDelay = new();
        [FieldAttr(nst: 1856)] public float _idleRippleIntensity = 0.015f;
        [FieldAttr(nst: 1860)] public float _underwaterRippleIntensity = 0.06f;
        [FieldAttr(nst: 1864)] public float _underwaterRippleRadius = 25.0f;
        [FieldAttr(nst: 1868)] public float _enterExitWaterRippleRadius = 300.0f;
        [FieldAttr(nst: 1872)] public igRangedFloatMetaField _jumpRippleDelay = new();
        [FieldAttr(nst: 1880)] public igRangedFloatMetaField _jumpRippleHorizontalOffset = new();
        [FieldAttr(nst: 1888)] public float _jumpRippleIntensity = 0.25f;
        [FieldAttr(nst: 1892)] public float _jumpRippleRadius = 5.0f;
        [FieldAttr(nst: 1896)] public float _jumpRippleMaxForwardOffset = 300.0f;
        [FieldAttr(nst: 1900)] public float _cameraZOffsetFromWaterSurface = -200.0f;
        [FieldAttr(nst: 1904)] public float _gravityScale = 1.0f;
        [FieldAttr(nst: 1908)] public float _inAirGravityScale = 3.0f;
        [FieldAttr(nst: 1912)] public float _onGroundSideDragScale = 4.0f;
        [FieldAttr(nst: 1916)] public float _jumpHeight = 750.0f;
        [FieldAttr(nst: 1920)] public igVfxRangedCurveMetaField _submergeCurve = new();
        [FieldAttr(nst: 2004)] public float _timeToFullSubmerge = 1.0f;
        [FieldAttr(nst: 2008)] public float _submergeAmountToJump = 0.01f;
        [FieldAttr(nst: 2012)] public float _submergeDampeningFactor = 0.5f;
        [FieldAttr(nst: 2016)] public float _extraSubmergeDampeningDownwardThreshold = 500.0f;
        [FieldAttr(nst: 2020)] public float _extraSubmergeDampeningSlopeMultiplier = 2.0f;
        [FieldAttr(nst: 2024)] public float _submergeSpringMaxVelocity = 4000.0f;
        [FieldAttr(nst: 2028)] public bool _canSurfaceWithCollisionAbove = true;
        [FieldAttr(nst: 2029)] public bool _useSpringWhenSubmergingFromAir = true;
        [FieldAttr(nst: 2032)] public float _shallowDiveSubmergeThresholdRatio = 1.0f;
        [FieldAttr(nst: 2036)] public bool _canActivateSubmergeInAir;
        [FieldAttr(nst: 2040)] public float _enterSubmergeImpulse;
        [FieldAttr(nst: 2044)] public float _enterSubmergeImpulseDuration;
        [FieldAttr(nst: 2048)] public float _enterSubmergeImpulseWhileInAir;
        [FieldAttr(nst: 2052)] public float _enterJumpImpulse;
        [FieldAttr(nst: 2056)] public float _enterJumpImpulseDuration;
        [FieldAttr(nst: 2060)] public float _enterQuickJumpImpulse;
        [FieldAttr(nst: 2064)] public float _enterQuickJumpImpulseDuration;
        [FieldAttr(nst: 2068)] public float _minSubmergeTimeForMaxJump;
        [FieldAttr(nst: 2072)] public igVfxRangedCurveMetaField _jumpCurve = new();
        [FieldAttr(nst: 2156)] public igVfxRangedCurveMetaField _groundJumpCurve = new();
        [FieldAttr(nst: 2240)] public float _maxJumpDuration = 3.0f;
        [FieldAttr(nst: 2244)] public float _maxJumpHeightChangePerSecond = 1.0f;
        [FieldAttr(nst: 2248)] public float _quickJumpDuration = 0.6f;
        [FieldAttr(nst: 2252)] public float _maxFractionOfJumpBeforeCanSubmerge = 1.0f;
        [FieldAttr(nst: 2256)] public bool _enableVelocityPitch = true;
        [FieldAttr(nst: 2260)] public float _velocityPitchDamping = 0.15f;
        [FieldAttr(nst: 2264)] public float _minSpeedForVelocityPitch;
        [FieldAttr(nst: 2268)] public float _minAngleVelocityPitch = -65.0f;
        [FieldAttr(nst: 2272)] public float _maxAngleVelocityPitch = 50.0f;
        [FieldAttr(nst: 2276)] public float _jumpDampeningFactor = 0.5f;
        [FieldAttr(nst: 2280)] public bool _autoDriftOnDrasticAngleChange;
        [FieldAttr(nst: 2284)] public float _minAngleChangeForAutoDrift = 45.0f;
        [FieldAttr(nst: 2288)] public float _raycastOffsetAbove = 1000.0f;
        [FieldAttr(nst: 2292)] public float _raycastOffsetBelow = 1000.0f;
        [FieldAttr(nst: 2296)] public float _raycastOffsetGround = 1000.0f;
        [FieldAttr(nst: 2300)] public float _raycastOffsetForward;
        [FieldAttr(nst: 2304)] public float _raycastOffsetDown = 250.0f;
        [FieldAttr(nst: 2308)] public float _raycastRadiusForward = 150.0f;
        [FieldAttr(nst: 2312)] public igHandleMetaField _targetWaterSurfaceMaterial = new();
        [FieldAttr(nst: 2320)] public float _waterUpIgnoreGroundDelta = 40.0f;
        [FieldAttr(nst: 2324)] public float _raycastForwardMaxWorldZAngle = 60.0f;
        [FieldAttr(nst: 2328)] public float _onGroundDistance = 100.0f;
        [FieldAttr(nst: 2332)] public float _minFallingDistance = 100.0f;
        [FieldAttr(nst: 2336)] public bool _gravityEnabled = true;
        [FieldAttr(nst: 2340)] public EXBUTTON _diveButton = EXBUTTON.JUMP;
        [FieldAttr(nst: 2344)] public EXBUTTON _diveButtonSecondary = EXBUTTON.L2;
        [FieldAttr(nst: 2348)] public float _cameraAboveWaterOffset = 120.0f;
        [FieldAttr(nst: 2352)] public float _cameraBelowObstacleOffset = 15.0f;
        [FieldAttr(nst: 2356)] public float _minimumDiveDuration = 1.0f;
        [FieldAttr(nst: 2360)] public igVfxRangedCurveMetaField _diveLinearAccelerationVelocityCurve = new();
        [FieldAttr(nst: 2444)] public float _diveAccelerationTimeToMaxForwardSpeed = 2.0f;
        [FieldAttr(nst: 2448)] public igVfxRangedCurveMetaField _diveLinearCoastingVelocityCurve = new();
        [FieldAttr(nst: 2532)] public float _diveCoastingTimeFromMaxForwardSpeed = 2.0f;
        [FieldAttr(nst: 2536)] public igVfxRangedCurveMetaField _diveLinearBrakingVelocityCurve = new();
        [FieldAttr(nst: 2620)] public float _diveBrakingTimeFromMaxForwardSpeed = 2.0f;
        [FieldAttr(nst: 2624)] public float _diveGrindModelShakeStrength = 5.0f;
        [FieldAttr(nst: 2632)] public igHandleMetaField _diveGrindRumbleData = new();
        [FieldAttr(nst: 2640)] public float _onGroundModelOffset;
        [FieldAttr(nst: 2644)] public float _minJumpHeight = 600.0f;
        [FieldAttr(nst: 2648)] public float _landingImpactMinimumTime = 1.0f;
        [FieldAttr(nst: 2652)] public float _landingImpactRippleModifier = 1.5f;
        [FieldAttr(nst: 2656)] public float _turnBankMinRotationSpeed = 30.0f;
        [FieldAttr(nst: 2660)] public float _turnBankMaxRotation = 70.0f;
        [FieldAttr(nst: 2664)] public float _turnBankRotationAngleMax = 30.0f;
        [FieldAttr(nst: 2668)] public float _turnBankRotationDampening = 0.15f;
        [FieldAttr(nst: 2672)] public float _turnBankZOffsetMax = -30.0f;
        [FieldAttr(nst: 2676)] public float _turnBankNoseRotationMax = 60.0f;
        [FieldAttr(nst: 2680)] public igVfxRangedCurveMetaField _turnBankSpeedRatio = new();
        [FieldAttr(nst: 2764)] public float _speedPitchRotationAngleMax = 30.0f;
        [FieldAttr(nst: 2768)] public float _speedPitchRotationDampening = 0.1f;
        [FieldAttr(nst: 2772)] public igVfxRangedCurveMetaField _speedPitchAccelCurve = new();
        [FieldAttr(nst: 2856)] public float _quickDiveDepth = 100.0f;
        [FieldAttr(nst: 2860)] public float _splash1BankThreshold = 0.4f;
        [FieldAttr(nst: 2864)] public float _splash2BankThreshold = 0.69999999f;
        [FieldAttr(nst: 2868)] public float _splash3BankThreshold = 0.89999998f;
        [FieldAttr(nst: 2872)] public CEntity? _waterDummyEntity;
        [FieldAttr(nst: 2880)] public igHandleMetaField _matchingVehicleWaterFakeBoltPoint = new();
        [FieldAttr(nst: 2888)] public float _pitchFakeRotation;
        [FieldAttr(nst: 2892)] public float _stickThresholdToTrigger = 0.5f;
        [FieldAttr(nst: 2896)] public string? _fadeInTrickEvent = "TrickFadeIn";
        [FieldAttr(nst: 2904)] public string? _fadeOutTrickEvent = "TrickFadeOut";
        [FieldAttr(nst: 2912)] public string? _rollLeftTrickEvent = "Trick_Left";
        [FieldAttr(nst: 2920)] public string? _rollRightTrickEvent = "Trick_Right";
        [FieldAttr(nst: 2928)] public string? _diveTrickEvent = "TrickForward";
        [FieldAttr(nst: 2936)] public string? _backflipTrickEvent = "Trick_Back";
    }
}
